### ISSUE TITLE
Submit responses to reviews:  The response is not in the correct format

### ISSUE THREAD

**Issue by MaKaYar** [MicrosoftDocs/windows-uwp#4342] opened 2023-03-14 16:51 UTC
I used API from https://learn.microsoft.com/en-us/windows/uwp/monetize/submit-responses-to-app-reviews and yesterday I noticed it is not working:

My request:
POST: https://manage.devcenter.microsoft.com/v1.0/my/reviews/responses
Json body:
```
{
    "Responses": [
        {
            "ApplicationId": "9NBLGGH6BNG3",
            "ReviewId": "5944c1f1-11ef-3b5e-4253-e9f2fa06e08f",
            "ResponseText": "Hi! We are thrilled to see your amazing review.",
            "SupportEmail": "",
            "IsPublic": true
        }
    ]
}
```
Results:
```
{
    "code": 4012,
    "description": "Description: The response is not in the correct format, or some parameter which is required is missing., Exception: ",
    "data": [],
    "source": "ReviewResponseFD"
}
```

Request to **https://manage.devcenter.microsoft.com/v1.0/my/reviews/b3b01c5f-5e36-86df-5fb6-63c2320b2b2e/apps/9NBLGGH6BNG3/responses/info** also is not working:
Results: 400 Bad Request

Could you tell me the API had been changed?

**Comment by MaKaYar** [comment] 2023-03-29 11:15
@hickeys , @mattwojo , hey guys! Could you ask your dev team why the api is not working?

**Comment by stevewhims** [comment] 2023-05-04 17:35
Hi, @MaKaYar, and thanks for filing this issue. Apologies for our delay in responding; we're investigating.

Thanks!
-Steve

**Comment by hickeys** [comment] 2023-05-04 18:04
@MaKaYar 

I believe the API is working properly, and your request is malformed. Specifically, you need to provide a valid email address as a value for the "SupportEmail" parameter. You're currently passing an empty string.  SupportEmail is a required parameter, and the docs correctly list it as such.

If you encounter the same error once you've updated your request, please reopen this issue. In the meantime, I'm going to close this because no doc updates seem needed.

**Comment by MaKaYar** [comment] 2023-05-15 10:19
Adding any emails didn't help

**Comment by MaKaYar** [comment] 2023-05-15 10:24
@hickeys , also I was writing about the second api:
> Request to https://manage.devcenter.microsoft.com/v1.0/my/reviews/b3b01c5f-5e36-86df-5fb6-63c2320b2b2e/apps/9NBLGGH6BNG3/responses/info also is not working:
> Results: 400 Bad Request
- this api also is not working and there isn't any relations with an email.

**Comment by hickeys** [comment] 2023-05-15 17:27
@MaKaYar 

Thanks for this additional information. I'll follow up with the store team. To help their investigation, can you please reproduce the errors for each API, and reply here with the following values from the response headers:

MS-CorrelationId
MS-CV

These will help the store team investigate further.

**Comment by MaKaYar** [comment] 2023-05-17 11:42
Sure.

### Stage 1. Get app reviews to check the review exists and token is working:
https://learn.microsoft.com/en-us/windows/uwp/monetize/get-app-reviews

**Request:**
GET `https://manage.devcenter.microsoft.com/v1.0/my/analytics/reviews?applicationId=9NBLGGH6BNG3&startDate=01/01/2023 7:46:54 PM&filter=id eq '60619090-6dfa-5ba2-e411-29ee7a392d94'`

**Response:** 
🟢 200 OK
<details>
<summary>Response body</summary>

```
{
    "Value": [
        {
            "date": "5/4/2023 12:12:46 AM",
            "applicationId": "9NBLGGH6BNG3",
            "applicationName": "Disney Magic Kingdoms",
            "market": "US",
            "osVersion": "Windows 11",
            "deviceType": "PC",
            "isRevised": false,
            "packageVersion": "7.9.9.0",
            "deviceModel": "Generic Desktop",
            "productFamily": "PC",
            "deviceRAM": 16384,
            "deviceScreenResolution": "1920x1080",
            "deviceStorageCapacity": 244198,
            "isTouchEnabled": false,
            "reviewerName": "olivia and lorenzo",
            "rating": 5,
            "reviewTitle": "super fun",
            "reviewText": "love playing this game",
            "helpfulCount": 0,
            "notHelpfulCount": 0,
            "responseDate": null,
            "responseText": null,
            "id": "60619090-6dfa-5ba2-e411-29ee7a392d94",
            "siloId": null
        }
    ],
    "@nextLink": null,
    "TotalCount": 1
}
```
</details>
Response headers:

```
MS-CorrelationId: a2555751-30e7-4c62-951f-b9293bd18be7
```

So, it means the review exists and token is working  

### Stage 2. Get response info for reviews

https://learn.microsoft.com/en-us/windows/uwp/monetize/get-response-info-for-app-reviews

**Request:**
GET `https://manage.devcenter.microsoft.com/v1.0/my/reviews/60619090-6dfa-5ba2-e411-29ee7a392d94/apps/9NBLGGH6BNG3/responses/info`

**Response:**
🔴 400 Bad Request
Response Headers:
```
MS-CV: exFXTILKm0CCJ8b6.0
MS-CorrelationId: c26c7463-a1f8-40c1-aa89-47a819a9e714
MS-RequestId: c096db99-f83d-44ef-bd27-3fb1c85438c2
MS-ServerId: 000005
```
This endpoint is not working (but it worked before 11 March 2023)

### Stage 3. Submit response to reviews

https://learn.microsoft.com/en-us/windows/uwp/monetize/submit-responses-to-app-reviews
Request:
POST `https://manage.devcenter.microsoft.com/v1.0/my/reviews/responses`
</details>
</p>
<p>
<details>
<summary>Request body</summary>

```
{
    "Responses": [
        {
            "ApplicationId": "9NBLGGH6BNG3",
            "ReviewId": "60619090-6dfa-5ba2-e411-29ee7a392d94'",
            "ResponseText": "Hiya! Thanks so much for your entire review! We're extremely happy you like our game!",
            "SupportEmail": "support@gameloft.com",
            "IsPublic": true
        }
    ]
}
```
</details>
</p>
**Response:**

🔴 400 Bad Request
<p>
<details>
<summary>Response body</summary>

```
{
    "code": 4012,
    "description": "Description: The response is not in the correct format, or some parameter which is required is missing., Exception: ",
    "data": [],
    "source": "ReviewResponseFD"
}
```
</details>
</p>
Response headers:  

```
MS-CorrelationId: 17e6db72-558a-4be1-a413-1c0a22425471  
MS-RequestId: 75b29892-f0ef-4631-983c-919c14b63d7a  
MS-CV: gSlsZPq2Rk+O9gsG.0  
MS-ServerId: 000006  
```

This endpoint also is not working (but it worked before 11 March 2023)

**Comment by MaKaYar** [comment] 2023-05-19 09:24
@hickeys , please, tell me if you need something else to investigate the problem. My thanks

**Comment by MaKaYar** [comment] 2023-06-19 17:18
@hickeys, @stevewhims , hey guys. Sorry for disturbing, but resolving the issue is actually important for me. Do you have any updates or ETA at least?

**Comment by stevewhims** [comment] 2023-06-19 17:59
Based on the messages in this thread, it looks like @hickeys is following up with the Store team with the repro info you provided. I don't currently have contact info for the Store team, myself.

-Steve

**Comment by stevewhims** [comment] 2023-07-11 18:17
Hi, @MaKaYar, and sorry for the delay in responding. I'm currently trying to source a Microsoft Store product team member to help with this issue.

The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete. So in that sense, this probably isn't the best channel for this issue. However, since we're already trying to work the case here, I'll continue to do that.

But, FYI, for questions (or requests for help) regarding your specific scenario, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

As I say, I can (and will) continue to use this thread to try to get help with your issue in any case.

Thanks for your patience!
-Steve

**Comment by stevewhims** [comment] 2023-07-14 22:53
Hi, @MaKaYar. The current info we have is that the API isn't working properly at this time. So I've added an "IMPORTANT" note to the top of the topic explaining that, and linking to a manual way that you can respond to reviews.

I'll leave the issue open a while longer, to give you a chance to respond.

Many thanks for your patience!
-Steve

**Closed as completed** 2023-08-31 17:38 UTC
Labels: Pri3
