### ISSUE TITLE
Access network transfer speed api

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#2186] opened 2020-01-21 03:43 UTC
Access network transfer speed api

Currently, `MediaPlayerElement` has no debug panel info, while YouTube online player has many debug info, such as speed and video resolution, etc. And iOS's `AVPlayer` also has many debug info, enough to display info for developers to analysis the network status.
`MediaPlayerElement` should contains debug panel, but unfortunately they don't!

So I'm asking to help to develop network transfer api to developers, this is really helpful.
And if possible,I hope `MediaPlayerElement` can support debug panel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28556949-8291-f501-a82b-b8ee0c8f24e2
* Version Independent ID: 10dbdeba-444e-8e04-83d5-8f5c5bb8b9c3
* Content: [Networking and web services - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/)
* Content Source: [windows-apps-src/networking/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/index.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by hkhmsft** [comment] 2020-01-22 21:19
Hello @hupo376787 and thanks for submitting your feedback to our team. To follow-up, do you mind expanding on your submission and clarifying your ask? We'd like to incorporate your feedback correctly and more information will be helpful.

**Comment by hupo376787** [comment] 2020-01-22 21:40
Hi, I'm glad you guys acting so quickly.

My original thought is really simple, just know the network status of local machine, such as upload/download speed. Because I'm designing online video app, I want to know the network status while playing video.

YouTube online player has many debug info, such as speed and video resolution, etc.
This function should be done by MediaPlayerElement, but unfortunately they don't!

So that's why I'm asking you to help, and currently there's no api or third party extensions doing that. I tried network profile's data usage api, but it's not real-time. I will put on the code later, cause I'm still sleeping now, 06:00am here.
Thanks.

**Comment by stevewhims** [comment] 2020-02-13 01:18
Hi, @hupo376787, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation itself. For example, if you believe that the content is incorrect, or that info needed to succeed with a common scenario is missing.

But for feedback about the product, like this, you can click **Send feedback about** \> **This product**, and you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

I'll go ahead and close this issue now, since there's no action I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

-Steve

**Closed as completed by stevewhims** 2020-02-13 01:18 UTC
Labels: product-feedback, uwp/prod, communication/tech, Pri2
