### ISSUE TITLE
Allow customizing sound

### ISSUE THREAD

**Issue by lifebound** [MicrosoftDocs/windows-uwp#3808] opened 2022-05-03 12:26 UTC
There is an option to 'play a sound when pinning a window". This should also include the option to choose a wav file (ideally), or at least a set of predefined system sounds (alternative). At the very least it should be clear which Windows system sound is being used for those of us who want to change the sound.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Version Independent ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Content: [PowerToys Always on Top utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/always-on-top)
* Content Source: [hub/powertoys/always-on-top.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/always-on-top.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by GrantMeStrength** [comment] 2022-05-11 19:07
Opportunity to improve docs.

**Comment by mattwojo** [comment] 2022-05-11 20:02
@crutkas -- Is there someone that can help with adding this info to the docs? Or if it is captured elsewhere (in the PT repo?), I'm happy to add it myself.

**Comment by crutkas** [comment] 2022-05-11 21:48
Tracking / duplicate of https://github.com/microsoft/PowerToys/issues/15219

**Closed as completed by crutkas** 2022-05-11 21:48 UTC
Labels: doc-enhancement, dev-environment/prod, Pri1, powertoys/tech
