### ISSUE TITLE
need a graphics dx tool

### ISSUE THREAD

**Issue by halkelley** [MicrosoftDocs/windows-uwp#2114] opened 2019-12-02 22:00 UTC
graphics don't display properly on my PC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae0c6a92-ae7f-09f7-d55e-1e2b862e1e1e
* Version Independent ID: 993094c4-d88e-510d-af9c-b3829085b9cd
* Content: [Graphics diagnostics tools - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features#feedback)
* Content Source: [windows-apps-src/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-12-03 00:29
Hi, @halkelley, thanks for filing this issue. It doesn't look like something that I can fix by making a change to the documentation. But if there's something incorrect in (or missing from) this topic that I can fix, then please let me know. Note that this topic is about tools you can use while developing a DirectX software application; it's not about general consumer issues with graphics not displaying properly on a PC system. For that, see some options below.

You got here by clicking **Send feedback about** \> **This page**. But for questions/feedback about the product, you can click **Send feedback about** \> **This product**, and you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

I'll go ahead and close the issue, but you can still respond to it.

-Steve

**Closed as completed by stevewhims** 2019-12-03 00:29 UTC
