### ISSUE TITLE
Got Errors CS0234  to build generated projection source code on tutorial [Generate a C# projection from a C++/WinRT component, distribute as a NuGet for .NET apps - Windows apps]

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/windows-uwp#4023] opened 2022-08-31 01:34 UTC
Hi! Recently I'm tracing [Generate a C# projection from a C++/WinRT component, distribute as a NuGet for .NET apps - Windows apps] with updated resources but getting errors on compiling generated SimpleMathComponent.cs file. How can I avoid these?
I cannot avoid CS2034 by _#pragma_ because the code is generated in every build.

### What I updated were;
1) use VisualStudio 2022 Pro instead of 2019
2) use Microsoft.Windows.CppWinRT 2.0.22608.4 for _SimpleMathComponent_ because it is the latest.
2) use Microsoft.Windows.CsWinrt (2.0.0) instead of (1.0.1) for _SimpleMathProjection_ because it's the latest.
3) target platform version 10.0.22621.0 istead of 10.0.19041.0
4) target platform min. version 10.0.19041.0 istead of 10.0.17763
*both SDK, 10.0.22621.0 and 10.0.19041.0 are installed.

### The exact messages;
Error	CS0234	The type or namespace name '**_WindowsRuntimeHelperTypeAttribute_**' does not exist in the namespace 'WinRT' (are you missing an assembly reference?)	SimpleMathProjection	E:\Codes\GitHubRepos\CsWinRT\src\Samples\NetProjectionSample\_build\AnyCPU\Release\SimpleMathProjection\bin\SimpleMathComponent.cs

and

Error	CS0234	The type or namespace name '**_WindowsRuntimeHelperType_**' does not exist in the namespace 'WinRT' (are you missing an assembly reference?)	SimpleMathProjection	E:\Codes\GitHubRepos\CsWinRT\src\Samples\NetProjectionSample\_build\AnyCPU\Release\SimpleMathProjection\bin\SimpleMathComponent.cs

### It occurrs in lines;
[global::WinRT.WindowsRuntimeType("SimpleMathComponent")][Guid("C5294299-09C8-5F7F-9FAE-46993031C242")][global::WinRT.**_WindowsRuntimeHelperType_**(typeof(global::ABI.SimpleMathComponent.ISimpleMath))]
    internal interface ISimpleMath
    {...

and

[global::WinRT.WindowsRuntimeType("SimpleMathComponent")][global::WinRT.**_WindowsRuntimeHelperType_**(typeof(global::ABI.SimpleMathComponent.SimpleMath))]
    [global::WinRT.ProjectedRuntimeClass(typeof(ISimpleMath))]
    [global::WinRT.ObjectReferenceWrapper(nameof(_inner))]
    public sealed class SimpleMath : global::System.Runtime.InteropServices.ICustomQueryInterface, IWinRTObject, IEquatable<SimpleMath>
    {...

*two errors on two lines = four errors in total. The errors are indicated (by waved-under-line) at the part of above lines;
**_WindowsRuntimeHelperType_**

---
#### Document Details
[SimpleMathComponent.cs.txt](https://github.com/MicrosoftDocs/windows-uwp/files/9457621/SimpleMathComponent.cs.txt)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Version Independent ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Content: [Generate a C# projection from a C++/WinRT component, distribute as a NuGet for .NET apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by vmx17** [comment] 2022-08-31 06:19
I got reason by myself.
The **_Microsoft.Windows.CsWinrt (2.0.0)_** seems too early (it isn't stable?) to use. I change it to **_(1.6.5)_** the errors were disappeared and the consuming code worked.
Sorry to confuse you ... orz

**Comment by vmx17** [comment] 2022-08-31 06:32
If someone knows the way to use **_Microsoft.Windows.CsWinrt (2.0.0)_** formally, please make me clear. There seems no such winrt class named _**WindowsRuntimeHelperType**_. That's the reason why I did not close this thread.

**Comment by stevewhims** [comment] 2022-09-01 22:53
Hi, @vmx17, and thanks for filing this issue.

Note that there's no mention of `WindowsRuntimeHelperType` or `WindowsRuntimeHelperTypeAttribute` in the topic.

The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

For questions (or requests for help) regarding a specific scenario, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

It seems like there's nothing specifically wrong with this topic as written. So I'll go ahead and close the issue.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-09-01 22:53 UTC
Labels: apps/tech, Pri2, reunion/prod

**Comment by vmx17** [comment] 2022-09-02 09:11
Thanks stevewhims-san,
I'm sorry but I've put a question here just before again. Should I try Microsoft Q&A? I thought this group's sample program is the most nearly what I want to do. Though here seems about UWP, the most information is now shifting to WinUI3 (WAP).
Anyway, in this thread, I agree to close the issue. I may have to ask other point for CsWinRT(2.0.0).

**Comment by stevewhims** [comment] 2022-09-02 19:51
HI, @vmx17! Q&A should get you directly to the feature team. A writer can (and should) fix errors/omissions in the documentation. But for help with specific issues that aren't directly tied to the docs, the most efficient route is to use the kinds of resources I mention above.

Thanks!
-Steve
