### ISSUE TITLE
Error from "Create your first WinUI 3 project" tutorial

### ISSUE THREAD

**Issue by JVimes** [MicrosoftDocs/windows-uwp#3827] opened 2022-05-12 21:47 UTC
I'm following the tutorial's [second section, for non-packaged apps][1], and doing it for C# (not C++). I get the following when I do the final step, "Build and run":

> Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll  
The program '[20440] App1.exe' has exited with code 2148734499 (0x80131623).

[1]: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app#non-msix-packaged-create-a-new-project-for-a-non-msix-packaged-c-or-c-winui-3-desktop-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 project - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-05-12 22:18
Thanks, @JVimes. I believe the documentation is correct as written, so this doesn't seem to be a **Send feedback about** \> **This page** issue (that I can fix by updating docs). If you have the Windows App SDK 1.0.0 Stable packages installed, and you're not running elevated (as admin, for example), then following the tutorial will work.

But if DDLM and framework packages aren't registered for the caller, or if you're running elevated, then the bootstrapper can fail. And there might be other versions of the Windows App SDK for which things might not work (see https://github.com/microsoft/WindowsAppSDK/pull/2248).

Another alternative is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since it does feel more like a product support issue. But you can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-05-12 22:18 UTC
Labels: Pri1, reunion/prod, winui-conceptual/tech

**Comment by JVimes** [comment] 2022-05-12 23:52
Thanks, Steve. I was missing the runtime. I find the "[Downloads for the Windows App SDK][1]" page pretty confusing. 

[1]: https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
