### ISSUE TITLE
`co_await`-ing a std::chrono literal does not compile in latest versions of MSVC

### ISSUE THREAD

**Issue by daviddetweiler** [MicrosoftDocs/windows-uwp#1829] opened 2019-07-28 11:58 UTC
Title, co_await is not defined for std::chrono duration types anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd174fcd-dc5c-7536-9a12-0e7b5926e739
* Version Independent ID: b66899fb-46a5-ac2c-b9e0-a23ddb351b2b
* Content: [More advanced concurrency and asynchrony with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency-2.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-08-06 02:46
Hi, @daviddetweiler, I'm not able to reproduce the issue. I'm using the latest public SDK, latest public OS, latest Visual Studio 2019 and C++/WinRT NuGet and VSIX. I can follow the instructions at the start of [Concurrency and asynchronous operations](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/concurrency) to create a new project and set it up and paste in the code there, then I can go to this advanced topic and add the coroutine that waits 5s. It all builds and runs as expected.

~Steve

**Comment by daviddetweiler** [comment] 2019-08-06 05:22
Problem disappeared after a clean reinstall. My mistake.

**Comment by stevewhims** [comment] 2019-08-06 20:33
Thanks, David, I'll go ahead and close this, then.

Thanks!
~Steve

**Closed as completed by stevewhims** 2019-08-06 20:33 UTC
