### ISSUE TITLE
typo in example

### ISSUE THREAD

**Issue by rextanka** [MicrosoftDocs/windows-uwp#686] opened 2018-06-14 19:17 UTC
maybe related to #677

The .idl example for MainPage seems to have a typo. In the doc it declares a class in the following namespace

namespace BookstoreCPPWinRT

A series of compile errors will be generated in VS if the class is declared in this namespace.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MIDL2025	[msg]syntax error [context]: expecting &lt; near "MainViewModel"	Bookstore	C:\Users\nicho.DESKTOP-SFDCTEJ\source\repos\Bookstore\Bookstore\MainPage.idl	10	
Error	MIDL2025	[msg]syntax error [context]: expecting &lt; near "{"	Bookstore	C:\Users\nicho.DESKTOP-SFDCTEJ\source\repos\Bookstore\Bookstore\MainPage.idl	10	
Error	MIDL2026	[msg]cannot recover from earlier syntax errors; aborting compilation	Bookstore	C:\Users\nicho.DESKTOP-SFDCTEJ\source\repos\Bookstore\Bookstore\MainPage.idl	10	

I believe this to be incorrect and I changed it to

namespace Bookstore

I was then able to complete the example.

Thanks for providing this sample.

Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4db0aab-b906-9dec-381c-ceccc1e90c45
* Version Independent ID: 493a4c50-ffa1-5e32-c757-92306c952887
* Content: [XAML controls; bind to a C++/WinRT property - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-property.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-property.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by rextanka** [comment] 2018-06-14 19:31
It's the MainPage.idl example at this location in the doc:

https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#add-a-property-of-type-bookstoreviewmodel-to-mainpage

**Comment by stevewhims** [comment] 2018-06-14 20:01
Thanks, Nick! I've fixed that typo (and also just generally updated the tutorial to match the current VS template). I appreciate you spotting this and letting me know, apologies for the typo! I'll respond to the other thread, too, in case this is the root cause. Thanks again! ~Steve

**Comment by stevewhims** [comment] 2018-07-30 18:43
@rextanka, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2018-07-30 18:43 UTC

**Comment by rextanka** [comment] 2018-07-31 16:36
Thanks Steve, I think that's fine! All the best. - Nick
