### ISSUE TITLE
Facing Issue to send and receive file using Bluetooth RFCOMM in UWP c# app.

### ISSUE THREAD

**Issue by HBTest13** [MicrosoftDocs/windows-uwp#4626] opened 2023-09-22 10:32 UTC
@mattwojo @Karl-Bridge-Microsoft

I am using the below reference code Github link to send and receive files using Bluetooth RFCOMM in the UWP c# application.

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/devices-sensors/send-or-receive-files-with-rfcomm.md?plain=1

I am facing an error at line var attribute = attributes[SERVICE_VERSION_ATTRIBUTE_ID]

And i have used service_version_attribute_id value is **0x0300**
const uint SERVICE_VERSION_ATTRIBUTE_ID = **0x0300**;

We face the below error using the above SERVICE_VERSION_ATTRIBUTE_ID . 

**"The given key '768' was not present in the dictionary."**

Can you please help to solve this error and get this code working in the UWP c# application?
```[tasklist]
### Tasks
```

**Comment by Win2211** [comment] 2023-09-28 05:13
@mattwojo @Karl-Bridge-Microsoft Can you please take a look here and help us to solve this issue?

**Comment by HBTest13** [comment] 2023-09-28 07:08
@Karl-Bridge-Microsoft @mattwojo ,
Can you Please look here and help to find out what issue we are facing to send files using Bluetooth  RFCOMM in UWP c#?

**Comment by Karl-Bridge-Microsoft** [comment] 2023-09-28 17:48
Hi @HBTest13,

As this seems to be a product support question and not a doc issue, I'm going to close this Issue.

I suggest trying [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) to make a suggestion or to ask a product question.

In addition, for community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).

For completeness, here are a few more developer support resources.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) can be used to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Closed as completed by Karl-Bridge-Microsoft** 2023-09-28 17:48 UTC
Labels: product-question, Pri3

**Comment by HBTest13** [comment] 2023-09-29 06:12
@Karl-Bridge-Microsoft 
Thanks for the suggestion here, will get back to you if I receive any assistance via any support resource.
