### ISSUE TITLE
Update for VS 2019?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#2073] opened 2019-11-07 22:30 UTC
Solution Explorer in VS2019 appears not to include a References in the Project (for UWP) so it's not clear how to add a reference as described above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a031039-0b18-5af9-061a-e17e5916150f
* Version Independent ID: aee13544-1ef8-08b2-d732-f71b237cc8a8
* Content: [MIDI - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment] 2019-11-11 20:26
Hello, thanks for your feedback. I just tried to reproduce your issue. I installed VS 2019 (Professional Edition) and created a new C# UWP project. I do see a References node in Solution Explorer, and I was able to add the Microsoft General MIDI DLS for Universal Windows Apps extension to my app. It sounds like perhaps you have an installation issue either with Visual Studio or with the Windows SDK.

Since this doesn't appear to be a documentation issue, here are all of the developer support resources, for completeness.

- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support site](https://developercommunity.visualstudio.com/) explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com/) is available, and responsive. The former User Voice feature is now there on the Suggest a feature tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.
Thanks!

**Closed as completed by drewbatgit** 2019-11-11 20:26 UTC
Labels: doc-bug
