### ISSUE TITLE
Unclear implementation of App-Level back button

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#1499] opened 2019-02-23 07:31 UTC
I found difficulty implementing first 3 lines of code.
Where this first 3 lines of code goes.
see this link: https://www.c-sharpcorner.com/UploadFile/909697/everything-about-back-navigation-in-uwp/

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab5201c-d8c8-1804-a225-4420f66d77ea
* Version Independent ID: 2d217eac-b2cd-553a-970f-32bb043fc353
* Content: [Navigation history and backwards navigation (Windows apps) - Windows UWP applications](https://docs.microsoft.com/en-ca/windows/uwp/design/basics/navigation-history-and-backwards-navigation)
* Content Source: [windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment] 2019-04-30 17:19
Dupe of #1560 which is also calling out the unclear samples on this page.

**Closed as completed by jevansaks** 2019-04-30 17:19 UTC
Labels: winui/tech, doc-enhancement, duplicate
