### ISSUE TITLE
winrt::hstring titleAsHstring = syndicationItem.Title().Text(); 有空指针问题

### ISSUE THREAD

**Issue by banrieen** [MicrosoftDocs/windows-uwp#2229] opened 2020-02-13 08:35 UTC
Windows 控制台应用程序(C++/WinRT) 项目示例，winrt::hstring titleAsHstring = syndicationItem.Title().Text(); 过程出现空指针问题：
0x00007FF7AFB25B46 处有未经处理的异常(在 BeautyOfPrograming.exe 中): 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [C++/WinRT 入门 - UWP applications](https://docs.microsoft.com/zh-cn/windows/uwp/cpp-and-winrt-apis/get-started#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/blob/live/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-02-14 00:56
Hi, @banrieen, and thanks for filing this issue. When I follow along with the topic, and use the code examples, I'm not seeing the access violation that you're seeing on that line of code. I'm using the latest public version of Visual Studio (16.4.5), the latest public operating system and SDK (18362), and the latest public version of the CppWinRT NuGet package (2.0.200203.5).

The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation itself. For example, if you believe that the content is incorrect, or that info needed to succeed with a common scenario is missing. But I'm not seeing anything wrong with the content in this case.

For feedback about the product, you can click **Send feedback about** \> **This product**, and you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

I'll go ahead and close this issue now, since there's no action I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

-Steve

**Closed as completed by stevewhims** 2020-02-14 00:56 UTC
Labels: doc-bug, uwp/prod, platform/tech, Pri1

**Comment by banrieen** [comment] 2020-02-23 15:26
Thanks very much, @Stevewhims 
**My question code slices:** 

```
// main.cpp
#include "pch.h"

using namespace winrt;
using namespace Windows::Foundation;
using namespace Windows::Web::Syndication;

int main()
{
    winrt::init_apartment();

    Uri rssFeedUri{ L"https://blogs.windows.com/feed" };
    SyndicationClient syndicationClient;
    SyndicationFeed syndicationFeed = syndicationClient.RetrieveFeedAsync(rssFeedUri).get();
    for (const SyndicationItem syndicationItem : syndicationFeed.Items())
    {
        winrt::hstring titleAsHstring = syndicationItem.Title().Text();
        std::wcout << titleAsHstring.c_str() << std::endl;
    }
}
```

The error happen at this line:

```
for (const SyndicationItem syndicationItem : syndicationFeed.Items())
```

at first, I guess that maybe the network problem because I am at the shenzhen city in china; but when debug the line ```SyndicationFeed syndicationFeed = syndicationClient.RetrieveFeedAsync(rssFeedUri).get();``` run normally and got the content。

And I update the VS ，re-new the sample then run again it has no error. Because the sample code updated yet. **The new example code:**

```
﻿#include "pch.h"
#include "SysInfo.h"
#include "BasementAlgorithms.h"
#include "ClassicProblems.h"

using namespace winrt;
using namespace Windows::Foundation;

void HelloDatetime();
void RandomNum();

int main()
{
    init_apartment();
    Uri uri(L"http://aka.ms/cppwinrt");
    printf("Hello, %ls!\n", uri.AbsoluteUri().c_str());
}
```
_So, I think you may have updated the code in VS , but forgot to update the code in docs "https://docs.microsoft.com/zh-cn/windows/uwp/cpp-and-winrt-apis/get-started#feedback" at same time!_

**Comment by stevewhims** [comment] 2020-02-24 21:36
Hi, @banrieen, thanks for the extra info. The code that you're showing as "The new example code" is the code that's built into the Visual Studio project template. Creating a project based on that template is just the first step described in the topic. The topic then asks the reader to copy-paste some new code into the project. That's the code that includes the **SyndicationItem** loop. So, nothing has been updated; and the code in VS is not meant to match the code in the docs.

As I say, when I use the latest public versions of the tools and platform, I can't reproduce any problem in the **SyndicationItem** loop. Since this is a feedback channel to let us know when the documentation is incorrect or incomplete, I'm afraid there's nothing I can see to action here in the documentation.

-Steve
