### ISSUE TITLE
RHPROXY for the Intel Apollo Lake Series?

### ISSUE THREAD

**Issue by PascalTNL** [MicrosoftDocs/windows-uwp#1083] opened 2018-10-16 10:08 UTC
I am not a experienced ASL programmer so I hoped to find help here. 
I was trying to adapt the code given in the appendix to my Intel Atom E3950 Apollo Lake chip with Windows 10 Enterprise on it. But for some reason it does not work proberly (It just appears in the device manager but is not accessable when tested with the verificationmethods of the testtools or a own sample program with Windows.device.I2C/GPIO). Is there a difference in writing and using the methods in the RHPRoXY device on hardware like mine? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563be75d-5703-601b-b1e5-4b4d98be597d
* Version Independent ID: e754993a-b516-93fa-0fd0-4518d00d93aa
* Content: [Enable usermode access to GPIO, I2C, and SPI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enable-usermode-access#apendix)
* Content Source: [windows-apps-src/devices-sensors/enable-usermode-access.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/enable-usermode-access.md)
* Product: **windows**
* GitHub Login: @jordanrh1
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2020-02-06 03:45
Hi, @PascalTNL, and thanks for filing this issue. Here's a response from the feature team, please let me know if you're able to action the info and questions here.

"[...] my initial thoughts are that exposing I/O space on Intel processors to user mode applications is not possible, as IN/OUT are privileged instructions, so they would need to write a KM driver and expose that to user apps. [...] please investigate if the issue is that GPIO is not memory mapped, and we can go from there."

"Also, who is the manufacturer providing the UEFI on the device? Be aware that the ASL portion of this topic is actually code that gets embedded in the BIOS/UEFI. It's possible that your hardware is capable of the expected behavior, but your UEFI has a bug."

Thanks!
Steve

**Comment by stevewhims** [comment] 2020-04-07 04:37
I'll go ahead and close this issue now since it isn't currently being actioned.

Thanks!
Steve

**Closed as completed by stevewhims** 2020-04-07 04:37 UTC
Labels: windows/prod
