### ISSUE TITLE
Further image processing

### ISSUE THREAD

**Issue by steve3424** [MicrosoftDocs/windows-uwp#1239] opened 2018-11-20 01:57 UTC
So each frame is written on a Direct3D11Surface which we then convert to a CanvasBitmap object in order to draw onto the _surface we defined earlier. I am looking to instead take a frame and do further processing (cropping, color manipulations, etc.) for the purposes of image classification. I can't seem to find any info on how to do this. Is there any documentation on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by drewbatgit** [comment] 2019-10-18 19:19
Hi, thanks for reaching out with this question. The CanvasBitmap class is part of the Win2D API which is documented in a separate GitHub repo. There are various API listed there for manipulating and converting images in this format: https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasBitmap.htm

Issues in this repo are intended solely for issues related to the documentation and not for technical/developer support questions. But, here are all of the developer support resources that you can use to get support for this issue:

- The [Windows developer feedback site](https://wpdev.uservoice.com/) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support site](https://developercommunity.visualstudio.com/) explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com/) is available, and responsive. The former User Voice feature is now there on the Suggest a feature tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.
Thanks!

**Closed as completed by drewbatgit** 2019-10-18 19:19 UTC
