### ISSUE TITLE
Fall creators update

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#2032] opened 2019-10-22 21:57 UTC
This page talks about fall creators update - it refers to RS3 (16299).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 389ddc46-dc2d-bebb-a07b-431aee1da594
* Version Independent ID: 38771c69-2606-d9bc-76ea-27feedac3ce3
* Content: [Natural motion animations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/composition/natural-animations#feedback)
* Content Source: [windows-apps-src/composition/natural-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/natural-animations.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stmoy** [comment] 2019-10-29 21:16
@asklar - What is the specific bug? Are we referring to the wrong update? How should we fix this?

**Comment by asklar** [comment] 2019-10-30 03:38
No bug - I added the note because I didn't expect [internal] people to know what fall creators update meant, RS3/build number is easier to relate to.

**Comment by stmoy** [comment] 2019-10-31 21:40
Cool, thanks for clarifying. Closing this since it's not a bug bug 🐛

**Closed as completed by stmoy** 2019-10-31 21:40 UTC
Labels: eng-triaged, doc-bug
