### ISSUE TITLE
C++/WinRT Visual Studio (VSIX) does not exist in the Visual Studio Marketplace

### ISSUE THREAD

**Issue by gwcSoftware** [MicrosoftDocs/windows-uwp#333] opened 2018-03-15 22:57 UTC
"For C++/WinRT project templates, as well as C++/WinRT MSBuild properties and targets, download and install the C++/WinRT Visual Studio Extension (VSIX) from the Visual Studio Marketplace."

The C++/WinRT Visual Studio Extension mentioned in the above paragraph on the "Introduction to C++/WinRT" docs page could not be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf7899f-689a-80c4-2c94-9575f8fc5055
* Version Independent ID: b8873e37-f4cb-de98-46f2-f2eaf01e275d
* Content: [Introduction to C++/WinRT - UWP app developer | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md)
* Service: **unspecified**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2018-03-15 23:09
Hi, Gil! Yes, that's true, and in fact it's by design right at this moment but only because C++/WinRT (and the documentation for it) is still in a pre-release form. The documentation is marked pre-release, but we do understand that folks are keen to evaluate the technology and for that reason C++/WinRT is available in Windows Insider builds of the Windows SDK. Until the general availability of C++/WinRT when the VSIX is expected to be available, I would recommend the great info that you can find on https://kennykerr.ca/articles/ and https://moderncpp.com/.

**Comment by stevewhims** [comment] 2018-03-19 20:56
I'll close this, since we're still in the pre-release phase. Thanks for looking at the C++/WinRT content!

**Closed as completed by stevewhims** 2018-03-19 20:56 UTC

**Comment by stevewhims** [comment] 2018-05-01 20:52
Gil, the VSIX is now available here: https://aka.ms/cppwinrt/vsix. I've updated the topic.

**Comment by zhangl1201** [comment] 2018-10-09 07:08
I have installed C++/WinRT VSIX successfully today when I failed to find it in Visual Studio Installer.
And My partner has installed C++/WinRT as a individual component in Visual Studio Installer... Confusing

**Comment by stevewhims** [comment] 2018-11-01 22:53
@zhangl1201, I'm sorry for the inconsistent UI you and your colleague are seeing. My advice is just to follow the info in [Visual Studio support for C++/WinRT, and the VSIX](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-and-the-vsix). ~Steve
