### ISSUE TITLE
Incorrect Documentation for Rust Setup w VS Code

### ISSUE THREAD

**Issue by mmoo9154** [MicrosoftDocs/windows-uwp#3283] opened 2021-08-06 00:51 UTC
Well, there's not a lot to get wrong here, but they manage.  I've had Code installed for a long time (currently v1.59.0); I installed the rust installer for Windows (64 bit version) (cargo --version  --> cargo 1.54.0 (5ae8d74b3 2021-06-22); installed CodeLLDB, cargo'd up a new rustean Hello world!, set a break point and hit F5.

I get a dialog that says "Unable to find executable for '<my-dev-path>\my-first-rust\<your program>.exe' with a nice "Open 'launch.json'" button to click.  (Never mind that the docs here say there will be an "OK" button.)  That opens the launch.json file with a "Launch" and a "Debug" sections boiler-plated out, but non-functional since "<your program>.exe" is not a valid filename.

I guess I'll sidetrack into CodeLLDB land to see how to config it up, but I was really hoping I could just get a down-the-middle-of-the-rode VS Code+rust environment up and running so I could focus on learning rust instead of focusing on how to drive CodeLLDB. (sigh)

Not that there's anything wrong with learning the lldb toolchain.  It's pretty clear I'll need to before producing anything meaningful.  I just had hoped I didn't need to do that before starting on rust.  (And, worse, I've been around long enough to be pretty certain CodeLLDB will have its own set of distracting sub-dependencies to pull me even deeper into the rat hole of just getting this simple environment up and running.)  (faceplam)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2021-08-06 01:27
Hi, @mmoo9154, and thanks for filing this issue. I can repro the error message you're seeing if I click "No" when the walkthrough indicates that I should click "Yes". See the section (in this topic) named "Hello, world! tutorial (Rust with VS Code)", and the **Note** for step 5.

Clicking "No" there will still generate a `launch.json`, but it won't have the right contents. Once you've generated that incorrect file, you won't be prompted to regenerate it.

I would suggest deleting \first_rust_project\\.vscode\launch.json and then hitting F5 again in VS Code. You should then get the series of message boxes described in that **Note** for step 5.

The other thing in the repro steps that you list, that doesn't match the steps in the topic, is step 2 of the "Install Visual Studio Code" section (in this topic).

Thanks!
Steve

**Comment by stevewhims** [comment] 2021-08-24 22:14
I'll go ahead and close the issue since there doesn't seem to be an action necessary to change the content. You can still reply after the issue is closed.

Many thanks!
Steve

**Closed as completed by stevewhims** 2021-08-24 22:14 UTC
Labels: product-question, dev-environment/prod, windows-rust/tech
