### ISSUE TITLE
Please Add Easy Installation Via Visual Studio Installer

### ISSUE THREAD

**Issue by DavidElyk** [MicrosoftDocs/windows-uwp#3815] opened 2022-05-05 17:54 UTC
I think the title says it all. Please make it easier to install this Feature set via the Visual Studio Installer with two nice checkboxes one for C# and another for C++.

I look at the installation instructions and just go ugh. Will discuss not having any sort of Visual Editor another day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c95c3c2-b81a-5682-5187-9f1328f17cf5
* Version Independent ID: 1a4d4425-689e-4d3a-1248-a1dd5789d285
* Content: [Install tools for the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b)
* Content Source: [hub/apps/windows-app-sdk/set-up-your-development-environment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-05-05 19:31
Hi, @DavidElyk, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

But for feedback about the product, like this, you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-05-05 19:31 UTC
Labels: get-started/tech, Pri1, reunion/prod
