### ISSUE TITLE
A link back to the core device portal API documentation would be helpful

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/windows-uwp#367] opened 2018-03-21 00:52 UTC
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bfbae1-7ec0-3bcc-7993-1fb9c8e3df14
* Version Independent ID: 46f0c4bd-5d1f-55e1-82eb-d82d01f74c37
* Content: [Device Portal API reference for HoloLens - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-hololens)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-hololens.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-hololens.md)
* Service: **unspecified**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment] 2018-06-11 22:19
Thanks for the feedback, StephenHodgson,
This topic is actually a duplicate of https://docs.microsoft.com/windows/mixed-reality/device-portal-api-reference, so we no longer show it in our TOC structure. I will contact the owners of that page, however, and see if they can link back to our core device portal APIs.

**Closed as completed** 2018-07-03 18:35 UTC
