### ISSUE TITLE
Not getting the expected result when following the guide.

### ISSUE THREAD

**Issue by dhamacher** [MicrosoftDocs/windows-uwp#3994] opened 2022-08-12 23:13 UTC
Using this guide I am not able to set up a rust environment on Windows 10. I get access denied issues (oserror 5) when I try to build anything. However, doing the same in WSL on Windows works flawless. I installed VS2022 Community with the tools described in this guide.

![image](https://user-images.githubusercontent.com/2443514/184455475-d8e31344-3e32-4888-aea1-41498b39c2af.png)

![image](https://user-images.githubusercontent.com/2443514/184455504-e41bdd6d-5327-4453-90a0-9897dbd1dade.png)

![image](https://user-images.githubusercontent.com/2443514/184455551-a2bac99a-0a35-4d79-a979-10fa2805c46e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-08-16 00:07
Thanks, @dhamacher. I'll plan to test the steps in the article again when I get some time to do that.

-Steve

**Comment by stevewhims** [comment] 2022-08-16 22:03
Hi, @dhamacher,

I followed the steps in the topic on a fresh Windows 10 machine. I installed Visual Studio and the workloads recommended in the topic. Then I ran the 64-bit Rust installer and the Microsoft C and C++ (MSVC) toolchain. I confirmed Rust was installed as per the topic. Then, as the topic suggests, I went to the Rust Programming Language book on the Rust website and I followed along with the Hello, World! tutorial.

Everything worked as described in the documentation. I didn't go as far as installing Visual Studio Code, since it seems best to get a baseline by confirming that command-line development works, before building on that baseline and installing an IDE (thinking that if command-line dev doesn't work, then I wouldn't expect IDE development to). And for similar reasons I didn't continue to the following topic, which is about Rust for Windows, and the *windows* crate.

I'll go ahead and close the issue, since the documentation seems to still be correct as written.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-08-16 22:03 UTC
Labels: dev-environment/prod, Pri1, windows-rust/tech
