### ISSUE TITLE
'App' does not contain a definition for 'Run'

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/windows-uwp#2372] opened 2020-04-20 13:58 UTC
Step2 of https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands#instantiate-the-xamlapplication-object-in-the-entry-point-of-your-wpf-app results in: CS1061	'App' does not contain a definition for 'Run' and no accessible extension method 'Run' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?) Program.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba9095f-57b4-267d-8896-5375c68b01ee
* Version Independent ID: 514d7e51-6f16-8199-aabf-26ee901a6ed3
* Content: [Host a standard UWP control in a WPF app using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2020-04-20 15:12
I'm sorry you're running into this problem. I just ran through the instructions up through this step again and confirmed that it's working for me. Here are a couple of things you can check:

* If your project is not named MyWpfApp, did you remember to change the `MyWpfApp` references in the code example to the name of your project?
* When you copied in the Program class code in step 2, did you copy this inside the namespace brackets in the Program.cs code file? (by default, this namespace should be the name of your WPF project).

**Comment by mcleanbyron** [comment] 2020-04-20 16:16
Since this does not appear to be a bug with the article at this point, I'm going to close this issue for now. If neither of the previous suggestions work for you and you continue to encounter the same error after retrying the instructions, feel free to reopen this issue with more details.

**Closed as completed by mcleanbyron** 2020-04-20 16:16 UTC
Labels: support-request, resolved-by-customer, uwp/prod, apps/tech, Pri1

**Comment by OzBob** [comment] 2020-04-21 01:20
copy and paste error - docs are wonderful!
i pasted myUWPApp instead of myWPFapp into the Program.cs
thanks for your patience

**Comment by mcleanbyron** [comment] 2020-04-21 04:22
Great - I'm glad you figured it out!
