### ISSUE TITLE
No notification is printed when Bluetooth radio state is changed via Bluetooth setting 

### ISSUE THREAD

**Issue by priyankajigalur** [MicrosoftDocs/windows-uwp#3388] opened 2021-10-06 06:35 UTC
IAsyncAction radio(){
        for (Radio radio1 : co_await Radio::GetRadiosAsync())
                {
                    if(radio1.Kind() == RadioKind::Bluetooth)
                    {
                        printf("\t Priyanka  %ls\n", radio1.Name().c_str());
                        radio1.StateChanged(&Radio_StateChanged);
                    }
              }
}

void  Radio_StateChanged(Windows::Devices::Radios::Radio const& sender, Windows::Foundation::IInspectable const& args) {

    printf("\t Radio_StateChanged %ls\n", sender.Name().c_str());

}

**Comment by Karl-Bridge-Microsoft** [comment] 2022-10-28 18:07
Closing. No doc issue reported. 

For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).

For completeness, here are a few more developer support resources.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
The [Visual Studio developer community](https://developercommunity.visualstudio.com/) is available, and responsive. The former User Voice feature is now there on the Suggest a feature tab, if you want to lobby for a change, a feature, or to make a suggestion.
If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Closed as completed by Karl-Bridge-Microsoft** 2022-10-28 18:07 UTC
Labels: Pri3, no issue reported
