### ISSUE TITLE
How to establish the connection to /ext/remoteinput websocket

### ISSUE THREAD

**Issue by pkebets** [MicrosoftDocs/windows-uwp#862] opened 2018-08-02 06:43 UTC
1) What is the correct endpoint for /ext/remoteinput websocket
ws://xbox_ip:11443/ext/remoteinput websocket
or
wss://xbox_ip:11443/ext/remoteinput websocket

2) Should the xbox device portal be configured with valid cert or default untrusted is fine?

3) What OS edition or OS version the /ext/remoteinput websocket is supported from

4) Does /ext/remoteinput websocket interaction work for retail boxes as well as devkits and testkits?

5) Does /ext/remoteinput websocket interaction work under DevMode as well as RetailMode?

**Comment by ginami** [comment] 2018-08-02 15:08
Hi @pkebets -- what page in our docs are you referring to? (This will help me route your question to the correct author.) Thanks!

**Comment by bindusadu** [comment] 2018-08-02 15:25
Hi @ginami ,

We are trying to connect to a xbox retail kit using https://github.com/Microsoft/WindowsDevicePortalWrapper/blob/06b65c173bb79890a3134d0e183e211408a50069/WindowsDevicePortalWrapper/WindowsDevicePortalWrapper.Shared/DevicePortal.cs#L199

We tried to use default untrusted cert and a valid enterprise SSL cert, both times get the error "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

some references we used -
https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/uwp-remoteinput-api
https://github.com/Microsoft/WindowsDevicePortalWrapper
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-ssl
Thanks!

**Comment by pkebets** [comment] 2018-08-02 15:42
Hi @ginami 
Here are the references to the docs:

The author should be @WilliamsJason 

1) https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/uwp-remoteinput-api

2) https://github.com/MicrosoftDocs/windows-uwp/blob/51ca48aae747febe01efe4b1d377c606e3ca4e0c/windows-apps-src/xbox-apps/uwp-remoteinput-api.md

Thanks

**Comment by WilliamsJason** [comment] 2018-08-02 17:21
I'll answer these questions as best I can--

1. We only allow https and wss access to Device Portal on Xbox. So the second endpoint is the correct one.

2. Either cert type is fine, but I'm seeing a recent regression when trying to clear the certs which appears to require a factory reset to get the certificates back into a good state. I'm still investigating, but for now I would just use the default untrusted certificates (and you may have to factory reset to get them back into a known good state).

3. This endpoint is supported in the recovery version released for the general public, so as long as you are using that recovery or a newer preview recovery it will be supported.

4. and 5. The endpoint will work on any type of kit which is in dev mode. So a retail kit that has done the retail->devkit conversion, or the regular devkits and testkits.

**Comment by pkebets** [comment] 2018-08-02 17:49
@WilliamsJason , thanks a lot for detailed answers, we will follow it

**Comment by baclark774** [comment] 2018-10-12 19:51
@WilliamsJason Would it be possible to provide a command line example of a control to the websocket api using something like wscat or any other command line based websocket tool? I'm setting up a remote test api for our xbox's and have everything working except the remote inputs and could use a little nudge :-) Right now i'm using wscat but can't connect and send a keyboard down command. Any help with a working example would be immensely appreciated!

**Comment by zbc** [comment] 2019-03-07 20:29
Hi there,
I tried to make the websocket connection, but it cannot even connect to the endpoint. Is there any solution? Thanks.

**Comment by hurrikam** [comment] 2020-03-18 17:14
Hi @WilliamsJason, I'm having the same issue as @baclark774.
I'm pasting my sample Node.js code:

```
    const url = `wss://${deviceIp}:11443/ext/remoteinput`;
    const webSocket = new WebSocket(url);
    webSocket.on('open', () => {
        console.log('--------- Sending KEY')
        const buffer = new Uint8Array(3);
        buffer[0] = inputTypes.KEYBOARD_KEY_CODES;
        buffer[1] = key;
        buffer[2] = keyPressFlags.KEY_PRESS;
        webSocket.send(buffer);
        buffer[2] = keyPressFlags.KEY_RELEASE;
        webSocket.send(buffer);
    });
```

When I run the example the node app does nothing and hangs, waiting for the connection to be established. It stays in that state forever, and no exception is thrown.

**Comment by mattwojo** [comment] 2020-08-28 17:53
Thank you for taking the time to let us know about this issue. Due to the volume of feedback in our content, we are currently prioritizing new issues. It also sounds like this issue may be resolved, so closing.

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.

**Closed as completed by mattwojo** 2020-08-28 17:53 UTC
Labels: product-question, Pri3

**Comment by colmaengus** [comment] 2022-08-16 16:32
Has anyone managed to figure out how to get websocket connecting from node.js?

**Comment by EdoTrotta** [comment] 2022-09-09 13:35
I am having issues on connecting to `/ext/remoteinput` via webSocket. 

I am testing it on Postman and I have a stuck `CONNECTION`, nothing happens. Any clue @WilliamsJason ?

**Comment by colmaengus** [comment] 2022-09-20 14:59
If you are connecting to wss://xbox:11443/ext/remoteinput you need to include an origin header https://xbox:11443. As well as the auth of course.
