### ISSUE TITLE
co_await CoreApplication::RequestRestartAsync({}) returns NotInForeground, even if the app is in fact in foreground

### ISSUE THREAD

**Issue by axodox** [MicrosoftDocs/windows-uwp#2511] opened 2020-06-03 18:57 UTC
In our C++/WinRT XAML + Direct3D app we have added a button which would restart the app when some settngs are changed. While worked for a while, recently we noticed it stopped working, while our code did not change. 

The call returns NotInForeground even though the call is bound to an XAML button directly. Our app supports multiple instances, but always focuses on the default instance when launched from start menu.

Reinstalling the app does not help, could you please suggest what could cause this?

**Comment by stevewhims** [comment] 2020-06-09 21:14
Hi, @axodox, and thanks for filing this issue.

This feels more like a product question, or a support request, or a potential bug report, than feedback that's specifically about the documentation in a given topic. I've included some links below that might be appropriate for you.

Incidentally, for specific feedback about the documentation in a particular topic, you can visit that topic (perhaps the [CoreApplication.RequestRestartAsync](https://docs.microsoft.com/uwp/api/windows.applicationmodel.core.coreapplication.requestrestartasync) topic), and click **Send feedback about** \> **This page**. For example, if you believe that the documentation in that topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions (or requests for help) regarding your specific scenario, like this, one option is to visit a documentation topic and click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

-Steve

**Closed as completed by stevewhims** 2020-06-09 21:14 UTC
Labels: support-request, Pri3
