### ISSUE TITLE
System.Devices.Aep.IsPresent returns true at inappropriate time

### ISSUE THREAD

**Issue by melvyniandrag** [MicrosoftDocs/windows-uwp#2881] opened 2020-12-23 16:39 UTC
This issue is over 3 years old! https://stackoverflow.com/questions/45568345/windows-uwp-bluetooth-app-devices-showing-up-when-scanning-even-when-they-are-p

Device Watcher detects paired, powered off devices, even if you filter for IsPresent == true as is indicated in documentation. 

Maybe update the documentation to indicate that this doesn't  currently work,  or remove this from the API? The docs are pretty clear in saying we should use IsPresent, but then it doesn't work.

**Comment by Karl-Bridge-Microsoft** [comment] 2022-10-28 18:01
It appears that this was clarified in the StackOverflow thread (https://stackoverflow.com/questions/45568345/windows-uwp-bluetooth-app-devices-showing-up-when-scanning-even-when-they-are-p).

Closing this issue. Please open a new issue with more detail and links to docs that you think could be improved (the link provide is to a basic API ref page).

For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).

For completeness, here are a few more developer support resources.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
The [Visual Studio developer community](https://developercommunity.visualstudio.com/) is available, and responsive. The former User Voice feature is now there on the Suggest a feature tab, if you want to lobby for a change, a feature, or to make a suggestion.
If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Closed as completed by Karl-Bridge-Microsoft** 2022-10-28 18:01 UTC
Labels: doc-bug, Pri3
