### ISSUE TITLE
ms-photos:viewer?fileName uri scheme not working

### ISSUE THREAD

**Issue by jozefchutka** [MicrosoftDocs/windows-uwp#2500] opened 2020-05-30 22:00 UTC
Win 10 Home 1903 18362.836
Microsoft Photos 2020.19111.24110.0

Running `ms-photos:viewer?fileName=c:\users\userName\Pictures\image.jpg` opens the photos app but doesnt show the photo. It seems the fileName parameter is ignored. App is opened in some "collections" setion.

Is there any uri scheme for opening video from web (http://.../video.mp4)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae2608d3-38b8-2404-d138-1ba17772e72c
* Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
* Content: [Launch the default app for a URI - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app)
* Content Source: [windows-apps-src/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-default-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment] 2020-06-26 18:43
Thanks for filing this issue @jozefchutka. Could you submit this to our [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) platform? The community of Microsoft experts and engineers over there could have a better answer to your issue. Though, if you suspect this to be a product bug, you could file this through [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by jozefchutka** [comment] 2020-06-29 07:26
Hi @lastnameholiu , I tired posting the same on Q&A however after submission it showed **WAF v2 has determined your request exceeded the normal web request and has blocked your request.** 

I do not know if this is product bug or not, resolve the attribute on your side.

Free of charge? Yes, thanks for letting me submit bug on your software free of charge.

At this point, I believe I did enough to report the bug in MS software. If you need please resubmit into any other system you like.

**Comment by hkhmsft** [comment] 2020-10-30 17:27
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. Thanks once again for submitting your feedback.

**Closed as completed by hkhmsft** 2020-10-30 17:27 UTC
Labels: product-feedback, uwp/prod, processes-and-threading/tech, Pri1

**Comment by RiccardoRomagnoli** [comment] 2021-05-11 08:35
So... What is the resolution?

**Comment by molesmoke** [comment] 2023-10-04 02:41
Three years later and the docs are either still wrong or the scheme still doesn't work?

**Comment by Pfaeff** [comment] 2023-11-15 14:54
It seems like it. It says 10/21/2022 on the site, so I presume it's not meant to be outdated. But it just doesn't work as described.

**Comment by xueshaoyu** [comment] 2024-02-28 07:57
4 years later，it's always error

**Comment by jozefchutka** [comment] 2024-02-28 08:23
@hkhmsft closed this issue in 2020, you might want to create a new one... But noone in Microsoft is interested nor will be looking into it.
