### ISSUE TITLE
Instructions in top-level rust windows tutorial for building Windows+Rust are obsolete

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/windows-uwp#4086] opened 2022-10-06 17:42 UTC
This page needs to be updated with current state of the art for building with the Windows crate. See https://github.com/microsoft/windows-rs/issues/1435 for the discussion. The error in the title of that issue arises directly from following the tutorial on this page.

The rss example docs need to be updated to the current state of building rust apps for windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://learn.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-10-06 19:45
Hi, @Paul-Dempsey, and thanks for filing this issue. I'll close this as a duplicate of https://github.com/MicrosoftDocs/windows-dev-docs/issues/3953. I've made a note of https://github.com/microsoft/windows-rs/issues/1435 in my internal work item, which I'll get to as soon as I can.

Thanks again!
-Steve

**Closed as completed by stevewhims** 2022-10-06 19:45 UTC
Labels: dev-environment/prod, Pri2, windows-rust/tech

**Comment by Paul-Dempsey** [comment] 2022-10-07 22:52
That item is marked completed on July 25, which is 2 1/2 months ago. I'd argue that your public work items should remain open until you've addressed the issue. Otherwise you'll get repeated filings for the same issue like this report. I searched for existing open issues regarding this looking for the correct instructions, but didn't find #3953, probably because you'd closed it without actually fixing the issue. I understand why you're doing this to manage your workload, but it isn't helpful to your readers.  You can easily link your github issues from your internal work item, so that you can close them when they are legitimate to close.

I looked at the OP's report o#3953, but I don't think it's complete wrt getting the Windows bindings. The samples repo still has a large quantity of boilerplate and no commentary or instructions, so I'm left a bit adrift on how to get started.
