### ISSUE TITLE
Incorrect grouping for "What's new in build 17763" and earlier SDKs

### ISSUE THREAD

**Issue by Sergio0694** [MicrosoftDocs/windows-uwp#1096] opened 2018-10-22 11:02 UTC
The "What's new in Windows 10 for developers, build 17763" category incorrectly groups the whole list of earlier SDKs instead of just the "API additions in Windows 10, build 17763" secondary page:

![image](https://user-images.githubusercontent.com/10199417/47289348-98fc1e00-d5fa-11e8-94d5-90d9ae86dcdd.png)

As a result, collapsing the "What's new, build 17763" collapses the whole list of previous SDKs, which is not the expected behavior.

Thanks! 😄

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d4c0f3b-3038-ac66-dcf0-09f8a51ec211
* Version Independent ID: 98ae5219-0a0d-863b-d296-7d47510a7a0b
* Content: [What's New in Windows 10 for Developers, Tools & Features - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-17763#feedback)
* Content Source: [windows-apps-src/whats-new/windows-10-build-17763.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-17763.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment] 2018-10-22 19:34
We want to ensure that the most recent What's New content is always clear, so we want to avoid excess top-level nodes within the What's New area. Because of that, this is currently expected behavior.

In light of this issue, however, I may test out an alternate solution. Stay tuned.

**Comment by Sergio0694** [comment] 2018-10-22 19:55
Hi @QuinnRadich - thank you for your answer.
I'm not sure I understand the reasoning behind this. Collapsing the "What's new in Windows 10, build 17763" node, this is the result:

![image](https://user-images.githubusercontent.com/10199417/47315358-a50ccd80-d644-11e8-9f9c-0bc85327b8dc.png)

So basically this is the only node that instead of collapsing the related APIs (for that same SDK), collapses the whole list of previous SDKs as well, which is just counterintuitive.
I want to note here, I'm not trying to argue or criticize anything here, just providing feedback for an already great docs website (can't stress enough how I _don't_ miss MSDN ahahah) 😊

Cheers!
Sergio

**Comment by martinekuan** [comment] 2018-12-07 05:42
Closing since this has been fixed.

<img width="278" alt="whats_new" src="https://user-images.githubusercontent.com/7740692/49629720-c1b85700-f99f-11e8-9100-52a6a5ede790.PNG">

**Closed as completed by martinekuan** 2018-12-07 05:42 UTC
