### ISSUE TITLE
C++/WinRT - Overload by type with MIDL 3.0

### ISSUE THREAD

**Issue by pontin-pdftron** [MicrosoftDocs/windows-uwp#3139] opened 2021-05-25 23:25 UTC
Hello,

I'm migrating my C++/CX to C++/WinRT component but I can't find a way to migrate my constructor overloads (by type) as it seems to not be supported on MIDL 3.0 when creating a projection.

For example:

```
runtimeclass MyClass
{
	MyClass();
	MyClass(Int32 index); // This should be my default overload
	MyClass(String name);
};
```

In C++/CX constructor overload is allowed by using `[Windows::Foundation::Metadata::DefaultOverload]` so my question is what is the alternative on C++/WinRT?

**Comment by stevewhims** [comment] 2021-05-27 00:40
Closing as duplicate of https://github.com/MicrosoftDocs/winrt-related/issues/239.

**Closed as completed by stevewhims** 2021-05-27 00:40 UTC
Labels: product-question, Pri3
