### ISSUE TITLE
access to D3D11Surface keeping resources on GPU

### ISSUE THREAD

**Issue by belveder79** [MicrosoftDocs/windows-uwp#1033] opened 2018-10-02 11:44 UTC
Concerning the Screen Capture code, https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture, I was wondering about a way to keep the captured resources on the GPU with the help of SharpDX, rather than bringing them to the CPU through CanvasBitmap.CreateFromDirect3D11Surface(...).

Basically the following code snippet should work out to copy the current Texture2D to a shared Texture2D, which can be used from that point on:

```
private void ProcessFrame(Direct3D11CaptureFrame frame) 
{
...

// original version: 
var canvasBitmap = CanvasBitmap.CreateFromDirect3D11Surface(
                    _canvasDevice,
                    frame.Surface);

// D3D11 Version:
// handle surface
IDirect3DDxgiInterfaceAccess interfaceAccess = frame.Surface as IDirect3DDxgiInterfaceAccess;
IntPtr pResourceIn = interfaceAccess.GetInterface(ID3D11Resource);
SharpDX.Direct3D11.Texture2D m_SrcTexture = new SharpDX.Direct3D11.Texture2D(pResourceIn);
SharpDX.Direct3D11.Device m_SrcDevice = m_SrcTexture.Device;
SharpDX.Direct3D11.DeviceContext m_SrcContext =  m_SrcDevice.ImmediateContext;
// shared resource
var sharedResourceDst = m_DstTexture.QueryInterface<SharpDX.DXGI.Resource>();
var sharedTexDst = m_SrcDevice.OpenSharedResource<SharpDX.Direct3D11.Texture2D>(sharedResourceDst.SharedHandle);
// copy to shared resource
m_SrcContext.CopyResource(m_SrcTexture, sharedTexDst);
m_SrcContext.Flush();
...
}
```

What I don't get is why the canvasBitmap is always valid (no matter which window is chosen), while the D3D11 version does work only for some windows. There is no D3D11 error, the resulting shared texture is just black/empty, and that's it. Is there a way to gain insight into what CreateFromDirect3D11Surface is making different?

**Comment by drewbatgit** [comment] 2019-10-18 19:22
Hi, thanks for reaching out with this question. This feels not so much like feedback specifically about the documentation, but rather like a question about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the [Windows developer feedback site](https://wpdev.uservoice.com/) (more info about that below).

Here are all of the developer support resources, for completeness.

- The [Windows developer feedback site](https://wpdev.uservoice.com/) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support site](https://developercommunity.visualstudio.com/) explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com/) is available, and responsive. The former User Voice feature is now there on the Suggest a feature tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.
Thanks!

**Closed as completed by drewbatgit** 2019-10-18 19:22 UTC
