### ISSUE TITLE
What is the C++/WinRT equivalent for the following C++/CX code?

### ISSUE THREAD

**Issue by MRahilly** [MicrosoftDocs/windows-uwp#3864] opened 2022-05-31 12:47 UTC
// Show the MessageDialog
    cancellationTokenSource = cancellation_token_source();
    task<IUICommand^> showTask = create_task(msgdlg->ShowAsync(), cancellationTokenSource.get_token());
    showTask.then([this, timer](task<IUICommand^> thisTask)
    {
        // . . .
    });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd174fcd-dc5c-7536-9a12-0e7b5926e739
* Version Independent ID: b66899fb-46a5-ac2c-b9e0-a23ddb351b2b
* Content: [Advanced concurrency and asynchrony with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency-2.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-05-31 19:01
Thanks, @MRahilly. This looks like a duplicate of https://github.com/MicrosoftDocs/windows-uwp/issues/3242. For #3242, I left a message on there saying that I've created a backlog work item for myself, and I'll get to that when I'm able. Once I start work on that work item, I'll return to #3242 and reopen it (my work item has a link to #3242, so they're linked). Since this issue right here is a duplicate, I'll go ahead and close it.

Thanks!
Steve

**Closed as completed by stevewhims** 2022-05-31 19:01 UTC
Labels: uwp/prod, platform/tech, Pri2
