### ISSUE TITLE
Segoe MDL2 Assets Font Download Is Not Latest Version

### ISSUE THREAD

**Issue by SkyeHoefling** [MicrosoftDocs/windows-uwp#2320] opened 2020-03-26 14:15 UTC
The provided font download link appears to be out of date. When I compare the available Glyphs in the downloaded font vs what is in `C:\Windows\Fonts` there are missing Glyphs. 

* Font Download (from this page) - https://aka.ms/SegoeFonts
* Version: 1710

My use case:
I am an app developer and I am using the fonts to have a cross-platform look and feel. Using the provided font download has made it easy to include in my project for other non-windows platform. When attempting to use the SignOut font (F3B1) I was getting invalid Glyphs in the app. After further inspection the provided font stops at Glyph F1CC.

As a workaround I was able to grab the font from my `C:\Windows\Fonts`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#related-articles)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment] 2021-05-28 19:54
Just a note to let you know I'm working to get this feedback directed to the right people, but don't have anything to report just yet.

**Comment by hickeys** [comment] 2021-05-28 21:09
Duplicate of #2043

**Comment by Pises98** [comment] 2021-07-22 22:20
Where can I find V1.82?

**Comment by hickeys** [comment] 2021-08-27 18:53
This page was updated recently and the glyphs should be up to date.

**Closed as completed by hickeys** 2021-08-27 18:53 UTC
Labels: doc-bug, uwp/prod, design/tech, Pri1

**Comment by ghost** [comment] 2023-11-17 04:28
Not updated.
