### ISSUE TITLE
Missing symbols description

### ISSUE THREAD

**Issue by tulnov** [MicrosoftDocs/windows-uwp#2346] opened 2020-04-10 12:12 UTC
When testing "Segoe UI and MDL2 icon font" version 1.60i
1. File "Segoe fonts v1710.zip" from url "Get the Segoe UI and MDL2 icon fonts" on page top contain font version 1.60i
2. Missing icons description from E001 to E454 (previously attended)
3. Missing icons description for EDE0, EE47, ЕЕ49, FOEF, F354, F6A9 and F6B8 icons
4. Missing icons description from F8A5 to F8B3

When testing version 1.82 (Windows 10 19603) questions 2-4 are present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment] 2021-05-28 19:51
Per the note in the doc - Glyphs with prefixes ranging from E0- to E5- (e.g. E001, E5B1) are currently marked as legacy and are therefore deprecated.

The remaining glyphs are completely documented on this page. It sounds like this issue is related to the font file itself, but unfortunately GitHub issues in the docs repo are only used for tracking documentation issues - not issues in the corresponding products and APIs. 

It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to report issues with products is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn

**Closed as completed by hickeys** 2021-05-28 19:51 UTC
Labels: doc-bug, uwp/prod, design/tech, Pri1
