### ISSUE TITLE
C++/WinRT code compiles but doesn't run

### ISSUE THREAD

**Issue by Gottfried007** [MicrosoftDocs/windows-uwp#4376] opened 2023-04-07 20:03 UTC
Your C++/WinRT code compiles but doesn't run. 
There is an exception:

"Unhandled exception at 0x00007FFEFD74CD29 in ND2D1DX11.exe: Microsoft C++ exception: winrt::hresult_wrong_thread at memory location 0x000000D4EFD2ED08."

_____________________________
Exception thrown at 0x00007FFEFD74CD29 (KernelBase.dll) in ND2D1DX11.exe: WinRT originate error - 0x8001010E: 'The application object must initially be accessible from the multi-threaded apartment.'.
'ND2D1DX11.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'.
onecoreuap\shell\coreapplication\application\lib\ApartmentHelpers.h(22)\twinapi.appcore.dll!00007FFEF62F60DC: (caller: 00007FFEF62C3F32) ReturnHr(1) tid(50fc) 8001010E The application called an interface that was maintained order for a different thread.
     CallContext:[\AppRunOrActivateView]
onecoreuap\shell\coreapplication\application\lib\coreapplication.cpp(77)\twinapi.appcore.dll!00007FFEF62F60F7: (caller: 00007FFEF62C3F32) ReturnHr(2) tid(50fc) 8001010E The application called an interface that was maintained order for a different thread.
     CallContext:[\AppRunOrActivateView]
onecoreuap\shell\coreapplication\application\lib\coreapplicationfactory.cpp(147)\twinapi.appcore.dll!00007FFEF630FCA8: (caller: 00007FF67DE729D2) ReturnHr(3) tid(50fc) 8001010E The application called an interface that was maintained order for a different thread.
Exception thrown at 0x00007FFEFD74CD29 in ND2D1DX11.exe: Microsoft C++ exception: winrt::hresult_wrong_thread at memory location 0x00000058DC2FED28.
Unhandled exception at 0x00007FFEFD74CD29 in ND2D1DX11.exe: Microsoft C++ exception: winrt::hresult_wrong_thread at memory location 0x00000058DC2FED28.

Exception thrown at 0x00007FFEFD74CD29 (KernelBase.dll) in ND2D1DX11.exe: WinRT originate error - 0x8001010E: 'The application called an interface that was being held in order for a different thread.'.
Exception thrown at 0x00007FFEFD74CD29 in ND2D1DX11.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x00000058DC2FEF68.

Unhandled exception at 0x00007FFEFD74CD29 in ND2D1DX11.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x00000058DC2FEF68.

Thread 0x1e1c terminated with code 0 (0x0).
Thread 0x5a98 terminated with code 0 (0x0).
Thread 0x6154 terminated with code 0 (0x0).
Thread 0x1138 terminated with code 0 (0x0).
Program '[15580] ND2D1DX11.exe' exited with code 0 (0x0).
______________________

https://learn.microsoft.com/en-us/windows/uwp/composition/composition-native-interop

Microsoft Visual Studio Community 2022
Version 17.5.3
VisualStudio.17.Release/17.5.3+33516.290
Microsoft .NET Framework
Version 4.8.04084
Visual C++ 2022   00482-90000-00000-AA996
Microsoft Visual C++ 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a3cc41b-0198-62e8-47be-4a76b7d4b112
* Version Independent ID: 548d8b37-819f-557b-173b-66e7188f9205
* Content: [Composition native interoperation - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/composition/composition-native-interop)
* Content Source: [uwp/composition/composition-native-interop.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/composition/composition-native-interop.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment] 2023-05-02 23:29
Hi, @Gottfried007, and thanks for filing this issue. I just followed along with the topic, and everything worked as expected. No exception.

I'm using an up-to-date version of Visual Studio 2022. There's a link in the "C++/WinRT usage example" section of this topic to info about Visual Studio support for C++/WinRT, so I confirmed that I have the right bits installed. And I created a new Core App (C++/WinRT) project, and accepted the defaults. I then pasted in the source code from the topic. It built and ran as expected.

I'll go ahead and close this particular issue, as I don't find anything wrong with the docs.

Here are all of the developer support resources, in case they're of help/interest:
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.


-Steve

**Closed as completed by stevewhims** 2023-05-02 23:29 UTC
Labels: uwp/prod, platform/tech, Pri2

**Comment by Gottfried007** [comment] 2023-05-03 07:58
"I created a new Core App (C++/WinRT) project"

I think that is the part I am not able to achieve because I can't find the template in all the lists I have.
Do I need to install the "Universal Windows Platform Development" Workload to access that template by any chance???
Because I thought that C++/WinRT being a header only technology/API, I would simply need to tinker a bit with the configuration file of any regular project. Several other C++/WinRT projects seem to compile and work completely fine with my current setup.

In any case, installing the whole "Universal Windows Platform Development" Workload needs 16Go of space on my system hard drive which I currently absolutely do not have. It's such a shame that such simple projects need so much unnecessary other stuff.

Also, I have no idea why so many Microsoft tools need to cram everything specifically on the system hard drive. I am absolutely tired of tinkering with NTFS links. I would have hoped windows 10 made progress in comparison to windows 7 in that aspect.
