### ISSUE TITLE
API request - BLE peripheral bond keys

### ISSUE THREAD

**Issue by epatstarkey** [MicrosoftDocs/windows-uwp#4864] opened 2024-02-12 18:26 UTC
### Type of issue

Other (describe below)

### Feedback

The WinRT project directed me here to make a conceptual suggestion for the WinRT API.

We work with BLE programmers that as part of their API provide the ability to serialize, deserialize, and read the bond keys exchanged with a BLE peripheral when paired. This includes things like EDIV/RAND/LTK/CSRK/IRK. 

I would like to request an API on https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth?view=winrt-22621 that brings the Windows Runtime API to the same level of functionality, at least on PC.

Something along these lines:

```
interface IBleBondKeys
ulong CentralIdentityAddress
int CentralIdentityAddressType
ulong PeripheralIdentityAddress
int PeripheralIdentityAddressType
byte[] LongTermKey
ulong Random
ushort Ediv
byte[] IdentityResolvingKey
byte[] ConnectionSignatureKey
```

Which could be added to a store for a specific BluetoothAdaptor, and retrieved for a specific BluetoothDevice on that BluetoothAdaptor.

Similar functionality is available on Linux, https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/settings-storage.txt and most of the main BLE stacks (Apache mynewt/nimble, nordic softdevice, Mbed BLE, etc).

**Comment by stevewhims** [comment] 2024-02-22 22:18
Hi, @epatstarkey, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

For feature requests to the product team, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2024-02-22 22:18 UTC
Labels: Pri3
