### ISSUE TITLE
Main uses await 

### ISSUE THREAD

**Issue by DamianMehers** [MicrosoftDocs/windows-uwp#3915] opened 2022-07-03 09:35 UTC
The example code uses `await` however `main` is declared `void`

```
static async void Main(string[] args) {
```

```
await mainInstance.RedirectActivationToAsync(activatedEventArgs);
```

@stevewhims I think you need to apply the second half of the @imechZhangLY [issue](https://github.com/MicrosoftDocs/windows-uwp/issues/3667) now that Main is  no longer `async`

```
var activatedEventArgs = Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c675e4ec-a22b-c54d-e1d6-1eaa408180b9
* Version Independent ID: c675e4ec-a22b-c54d-e1d6-1eaa408180b9
* Content: [Application lifecycle functionality migration - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle?hmsr=joyk.com&utm_source=joyk.com&utm_medium=referral)
* Content Source: [hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-07-05 22:35
Hi, @DamianMehers, and thanks for filing this issue.

I did update the inline code example in that topic when the sample changed; but either I didn't update it enough, or the sample has changed again. Either way, it's seems like better economy to link to the sample apps instead of making a duplicate of some of its code, and then trying to keep that fully maintained. So I've published an update to the topic along those lines.

Thanks again!
-Steve

**Closed as completed by stevewhims** 2022-07-05 22:35 UTC
Labels: get-started/tech, Pri2, reunion/prod
