### ISSUE TITLE
Using MIDI API hangs the app on exit

### ISSUE THREAD

**Issue by IgorX2** [MicrosoftDocs/windows-uwp#1426] opened 2019-01-28 18:59 UTC
When using the `MidiInPort` example demonstrated here to listen for MIDI messages, the app hangs on exit, even when all resources have been disposed properly (as described in the article under _Create MIDI ports to send and receive messages_). This happens even on minimal examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by EddieLotter** [comment] 2019-01-28 19:32
@IgorX2 does this happen to you when you use the sample provided by Microsoft?
http://go.microsoft.com/fwlink/p/?LinkId=620571

**Comment by IgorX2** [comment] 2019-02-02 08:27
@EddieLotter Yes, it does. However, I have found that moving the destructor logic to the Suspend method circumvents the problem. However, if the MIDI device is disconnected during app's execution, the problem occurs regardless of the workaround.

The MIDI device is M-Audio 88es Keyboard and the sound card is M-Audio FastTrack.

**Comment by drewbatgit** [comment] 2020-08-28 17:49
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue.

GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) site is the home for technical questions and answers at Microsoft.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.

**Closed as completed by drewbatgit** 2020-08-28 17:49 UTC
Labels: support-request, uwp/prod, Pri2
