### ISSUE TITLE
Does not explain how to uninstall when all else fails

### ISSUE THREAD

**Issue by fernan** [MicrosoftDocs/windows-uwp#3672] opened 2022-02-18 17:08 UTC
I have uninstalled PowerToys and want to install a new version, however the new installer (v.0.55.1) complains that there is another PowerToys version installed. The Add/Remove software shows nothing. The document does not explain how to uninstall remaining pieces (where should we look for in the system? Which folders should we remove? Which registry entries? etc. )
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment] 2022-03-22 05:54
Duplicate of https://github.com/microsoft/PowerToys/issues/16845

**Comment by mattwojo** [comment] 2022-05-19 20:11
Thank you Jay for adding the uninstall script in https://github.com/MicrosoftDocs/windows-uwp/pull/3836

Closing this out, but will keep an eye out for any further uninstall updates based on https://github.com/microsoft/PowerToys/issues/16845

Thanks for contributing and brining this issue to our attention!

**Closed as completed by mattwojo** 2022-05-19 20:11 UTC
Labels: doc-enhancement, dev-environment/prod, Pri2, powertoys/tech
