### ISSUE TITLE
The operation attempted to access data outside the valid range (Exception from HRESULT: 0x8000000B)

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/windows-uwp#1916] opened 2019-09-10 05:42 UTC
I'm getting a `The operation attempted to access data outside the valid range (Exception from HRESULT: 0x8000000B)` error on this line. What causes this?

`IReadOnlyList<StorePackageUpdate> storePackageUpdates = await context.GetAppAndOptionalStorePackageUpdatesAsync();`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3aae6d8-4751-8713-cb47-180ca2a1af01
* Version Independent ID: e46c9be3-742b-a831-5b7e-8363cd61bba9
* Content: [Download and install package updates from the Store - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates)
* Content Source: [windows-apps-src/packaging/self-install-package-updates.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/self-install-package-updates.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by myokeeh** [comment] 2019-09-14 20:44
@mcleanbyron Is this API broken?

**Comment by mcleanbyron** [comment] 2019-09-16 16:04
Thanks for reporting this issue. I have reached out to the engineering team that owns this API and will let you know what I find out.

**Comment by mcleanbyron** [comment] 2019-09-17 19:31
The engineering team has indicated that there have no changes to the code base for this API in a long time and there are no known issues with it.

**Comment by mcleanbyron** [comment] 2019-09-17 19:34
@myokeeh, can you confirm whether your project is associated with an app in the Store and this app has a published submission?

**Comment by myokeeh** [comment] 2019-09-17 19:37
Yes. The app has been published. It's a LOB app. Win 10 17763 or higher. I actually had this working on the app before but commented it out until now. That may have been a year ago. Now it's not working... Giving me that error. All of it is a copy and paste from the documentation.

________________________________

**Comment by mcleanbyron** [comment] 2019-09-17 20:05
Thanks, this is helpful. I'll pass this along to the engineering team. In the meantime, they indicated that it would be helpful if you submitted a bug for this using Feedback Hub and attach any logs you may already have (or use the "Recreate my problem" feature in Feedback Hub to record logs while your app is running).

**Comment by mcleanbyron** [comment] 2019-09-18 17:04
The engineering team unfortunately isn't able to reproduce the error. They tested the code example in a basic repro project where the app identity points to one of their test apps with package submissions in the Store, and it worked fine for them. Because this repoo is for the docs and is not intended to be a support channel for developer assistance, I'm closing this issue for now. 

The best way to get developer support is to consult our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and reopen the issue.

**Closed as completed by mcleanbyron** 2019-09-18 17:04 UTC
Labels: uwp/prod, deployment/tech, Pri2

**Comment by RokeJulianLockhart** [comment] 2024-12-23 20:22
> The best way to get developer support is to consult our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions).

@myokeeh, if you still see this, perhaps follow [`stackoverflow.com/q/62674275/9731176`](https://stackoverflow.com/q/62674275/9731176). Otherwise, can you advise on how you remediated it? I ask because I see the same error when diagnosing https://github.com/nextcloud/desktop/issues/6422#issuecomment-2543398921, and there aren't many instances of this on the internet.
