### ISSUE TITLE
Accessing files using standard libraries in C++ UWP APp

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [MicrosoftDocs/windows-uwp#1504] opened 2019-02-27 18:59 UTC
From C++ UWP app, some of the system files can be accessed by using standard library functions without declaring broadFileSystemAccess in the manifest file. Also WACK does not catch this as an error, "Supported API" test is passed.
Documentation does not mention about this. 
 Is it ok to develop production code with accessing files in Windows folder by using standard library functions in C++ UWP App?
Thanks

**Comment by ginami** [comment] 2019-03-01 02:38
Hi @armstrong-charles -- which doc do you think should include this information? (This will help me route your comments to the correct author.) Thank you!

**Comment by stevewhims** [comment] 2019-10-18 01:02
Hi, @armstrong-charles. It's been a while since the request for more info.

Without more specific info, this question feels not so much like feedback specifically about the documentation, but rather like a question about the product.

To leave feedback about documentation content, you can go to a topic and click **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no actionable info here to know what change to make to any particular documentation topic.

Thanks!
Steve

**Closed as completed by stevewhims** 2019-10-18 01:02 UTC
