### ISSUE TITLE
New customers can (we add) be deleted  while existing customers cannot

### ISSUE THREAD

**Issue by flotsam7jetsam** [MicrosoftDocs/windows-uwp#2367] opened 2020-04-16 14:57 UTC
I noticed that when I add a customer, I can delete that customer. However, it seems that existing customers cannot be deleted from the database. For example, I've found that the customer Xavier Smith cannot be deleted using the code as it stands today. Nevertheless, great tutorial.

When debugging I noticed that GUID for Xavier within SQLite is:
{ d44c441c - ecda - 4eae - 8869 - b2b7147c7246}

and the GUID c# is looking for is:

{d44c441c-ecda-4eae-8869-b2b7147c7246}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4973ee6-8a33-75d3-f942-129628377fdb
* Version Independent ID: 0c933c8f-6dbb-cb14-fce3-9ca724b18d82
* Content: [Create a customer database application - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/enterprise/customer-database-tutorial)
* Content Source: [windows-apps-src/enterprise/customer-database-tutorial.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/enterprise/customer-database-tutorial.md)
* Product: **uwp**
* Technology: **app-types**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2020-10-30 17:44
Thanks for your feedback on the sample, and I'm glad you got some value out of the tutorial. I am following up to confirm whether it is by design that the existing customers cannot be deleted from the provided database, and I will revise the article as necessary. In the meantime, I am closing this issue because there does not seem to be a doc bug with the article itself at this time. If you have further feedback, please feel free to reopen this issue with more details.

**Closed as completed by mcleanbyron** 2020-10-30 17:44 UTC
Labels: product-feedback, uwp/prod, app-types/tech, Pri2
