### ISSUE TITLE
1909 support

### ISSUE THREAD

**Issue by SmartmanApps** [MicrosoftDocs/windows-uwp#2162] opened 2020-01-10 03:10 UTC
I'm having an issue with a Xamarin UWP app on a device running 1909 which works fine on 1903. I can't rollback to 1903 because "updated more than 10 days ago". When is 1909 support being added? Still only goes up to 1903. Note: this may or may not be the reason for the issue, but hasn't been ruled out yet (it's the only lead I have at the moment though).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1ff7f3-d77d-b7bd-8dfa-7f25cb0b5239
* Version Independent ID: 71e57b3b-b25f-0299-2cbc-f895a98c685d
* Content: [Choose a UWP version - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version)
* Content Source: [windows-apps-src/updates-and-versions/choose-a-uwp-version.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/updates-and-versions/choose-a-uwp-version.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by bmwilson1978** [comment] 2020-03-19 22:52
We are having similar issues with two of our LoB applications, runs fine on 1803, 1909 seems to be a hot mess where they don't ever start correctly.  Windows Event log shows the apps are being killed by Windows for various reads such as Hung Thread or Navigation (Hang Type).

To be fair to developers and businesses, this whole UWP thing is a good example of something extremely pointless - MS aren't willing to admit they made a huge mistake on - however are more than happy to recommend it strongly to their customers with statements like "we're all in on this [insert tech]".

**Comment by hartez** [comment] 2020-04-07 16:39
@SmartmanApps So this is a Xamarin.Forms app? What's the problem you're seeing?

**Comment by hickeys** [comment] 2020-05-26 21:27
@SmartmanApps @bmwilson1978 

We'd like to follow up on this issue, but it seems like it's a little too complex to do via GitHub. Can one or both of you email me at hickeys@microsoft.com?

**Comment by hickeys** [comment] 2020-06-29 19:36
Based on some investigations, I can confirm 1909 support. The engineering team did not see anything that would cause the issues you're describing. Since there has been no reply on this issue, I'm going to close it. Please reopen if you continue to encounter this issue.

**Closed as completed by hickeys** 2020-06-29 19:36 UTC
Labels: product-question, uwp/prod, deployment/tech, Pri1
