### ISSUE TITLE
Is there a query limit on GetSubscriptionsForUser API on a per minute, hour or day basis?

### ISSUE THREAD

**Issue by mickeymoon** [MicrosoftDocs/windows-uwp#2395] opened 2020-04-28 10:32 UTC

**Comment by hickeys** [comment] 2020-12-14 19:46
There is no specific limit on this call.

I'm going to close this issue as your question has technically been answered, but I get the feeling there's more here. If you'd like further technical help, there are a number of places you can try:

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn

**Closed as completed by hickeys** 2020-12-14 19:46 UTC
Labels: product-question, Pri3
