### ISSUE TITLE
Unable to create app package

### ISSUE THREAD

**Issue by aquinn39** [MicrosoftDocs/windows-uwp#3544] opened 2021-12-06 09:29 UTC
After following the 'Package the app' section of the tutorial here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands, I am unable to create an app package for the app due to the following errors:

• Validation error. error 80080204: App manifest validation error: Line 217, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication" must only be declared once. A duplicate exists on Line 42, Column 27.	
• PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
• PRI222: 0x80073b0f - Unspecified error occurred.

I have added a reference to both the WPF app and the UWP app to the app package as per the tutorial as I would like to upload the app to the Microsoft Store. I am following this tutorial as I would like to use WinUI 2 with XAMLHost, which works fine when the WPF app is built outside of the package or if built inside the package without referencing the UWP app in the package.

App I am using is a new .NET Core 3.1 app and I have followed all of the requirements in the tutorial. There are no other packages or files that have been added.

It seems like this may have been broken in an update to Visual Studio as it used to work I believe.

I am using Visual Studio 2022 17.0.2.
I also tried using Visual Studio 2019 16.11.5.
Same issues with both.

Also reported this issue on Visual Studio Feedback here: https://developercommunity.visualstudio.com/t/Unable-to-create-Store-app-package/1668742 and Feedback Hub here: https://aka.ms/AAhjfmc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba9095f-57b4-267d-8896-5375c68b01ee
* Version Independent ID: 514d7e51-6f16-8199-aabf-26ee901a6ed3
* Content: [Host a standard WinRT XAML control in a WPF app using XAML Islands - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by aquinn39** [comment] 2021-12-08 16:19
I've downgraded to Visual Studio 2019 version 16.9.8 and this seems to have fixed all of the issues. I would much prefer to be able to use Visual Studio 2022 though or at least the latest version of 2019.

**Comment by aquinn39** [comment] 2022-02-19 17:25
I've reported this issue to Visual Studio Feedback: https://developercommunity.visualstudio.com/t/Unable-to-create-Store-app-package/1668742?port=1025&fsid=39faaef5-a58b-4a54-a337-8a160f88b801&entry=myfeedback&ref=native&refTime=1645291507519&refUserId=8bce036a-185d-4c7f-837f-f5f8df35f6a2

**Comment by stevewhims** [comment] 2022-02-26 03:16
Thanks, @aquinn39. I'm getting the same build error with VS 2022 17.1. I've reached out to the product team for info about this particular issue.

Meanwhile, I took a pass through the topic, because previously it was talking about VS 2019. Since the steps work (apart from the issue you're seeing) for VS 2022, I updated the topic and just generally tidied it up and simplified it a little.

I'll get back to you when I get more info.

Thanks!
-Steve

**Comment by aquinn39** [comment] 2022-04-29 21:52
Hi @stevewhims,

Do you have any updates on this?
I'd really like to use Visual Studio 2022 for many projects that have this issue but am still stuck using 2019 as 2022 can't build them (I've checked on the latest version at the time of writing this, 17.1.5).

**Comment by stevewhims** [comment] 2022-05-02 22:11
Thanks, @aquinn39. I've reached out again for info. I'll keep you posted; sorry about the delay.

-Steve

**Comment by aquinn39** [comment] 2022-09-29 17:36
This issue has also been reported here: https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32/issues/328 and here: https://developercommunity.visualstudio.com/t/Visual-Studio-16100-breaks-support-for/1634426?q=microsoft.toolkit&ftype=problem&space=8&stateGroup=active&sort=newest

**Comment by stevewhims** [comment] 2022-09-29 19:06
Thanks for the reminder. I've reached out again for info.

-Steve

**Comment by stevewhims** [comment] 2022-11-23 22:50
I've just made a small change to this topic (and 6 others like it). I added a note to draw attention to [the support notice](https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32#xaml-islands-notice) in the GitHub repo for the Windows Community Toolkit. All the relevant details are in that notice.

At the moment, it's not clear whether the problem is with the Windows Community Toolkit or with Visual Studio. At the same time, it's not clear that there are any changes that need to be made to the documentation in this topic. In light of all of that, and the age of this issue, I'm going to go ahead and close it. I'll be more than happy to reactivate it, and fix the topic, if anything concrete comes up that needs fixing.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-11-23 22:50 UTC
Labels: uwp/prod, apps/tech, Pri2
