### ISSUE TITLE
Surprise removal while executing an ID3D11Query

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-uwp#1634] opened 2019-04-30 15:34 UTC
How is an application expected to handle this scenario?  If the GPU is removed, and the application is executing this code (sample from https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nn-d3d11-id3d11query):

while( S_OK != pDeviceContext-&gt;GetData(pQuery, &queryData, sizeof(queryData), 0) )
{
}

GetData continues to return S_FALSE before and after the GPU is removed, and the app is left looping forever.  It also never makes it to a present call or calls ResizeBuffers, so it does not know that a device was removed.  How should this be handled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7f0b243-b9be-394f-0ba7-7edae3d8336f
* Version Independent ID: 6831be54-f930-caca-1898-e8c900837706
* Content: [Handle device removed scenarios in Direct3D 11 - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/handling-device-lost-scenarios)
* Content Source: [windows-apps-src/gaming/handling-device-lost-scenarios.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/handling-device-lost-scenarios.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment] 2019-10-17 23:37
Hi, @englishb. I'm really sorry for the long delay in responding, and thanks for filing this issue.

You make a good point, and I'm not certain whether the remedy here is to change the loop condition so that we can break out of it if/when a removal is detected, or whether the tight loop is meant to remain but be executed on a different thread from the thread that detects removal. It seems that if this `while` loop were executed asynchronously on its own thread, then that would allow the Present/ResizeBuffers thread to reach code that could detect a removal and respond to that.

In light of my uncertainty around what (or whether) change to make to the documentation, this currently qualifies as a product support question. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Also, you make the point that S_FALSE is being returned even after removal. If that turns out to be a product bug, then that's something that Microsoft Support would be able to diagnose and determine.

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.

I'm sorry that I couldn't be of more immediate help with this issue.
-Steve

**Closed as completed by stevewhims** 2019-10-17 23:37 UTC
Labels: product-question
