### ISSUE TITLE
Dev Drive support for LongPathsEnabled

### ISSUE THREAD

**Issue by noopman** [MicrosoftDocs/windows-uwp#4739] opened 2023-11-19 07:25 UTC
On my fully updated Windows 11 system I have set [LongPathsEnabled](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation). I have kept my code in c:\code. All of the files there are in git. Among the things I use is [AzOps](https://github.com/Azure/AzOps) which copes the structure of our Azure Tenant into a file system, for Azure operational reasons, and checks this into Git. It requires LongPathsEnbabled. I also configure git to accept the same

```
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

git config --system core.longpaths true
```

I have set up my Dev Drive on D. (D for Dev.)

When I copy all my files from c:\code to d:\ it prompts me that "Destination Path is too long" about specifically a file in that AzOps catalogue.

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/300622/3e58c61f-6cdd-4fe3-968e-a4018fd529a0)

According to Bing AI ReFS does not support the long paths. "This is because ReFS uses the same Win32 API that restricts the path length for users".

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/300622/9e3a5f97-6133-4d4a-aa3b-8e0fcc98a186)

Would it be possible to implement support for long file paths in ReFS?

**Comment by noopman** [comment] 2023-11-19 07:26
At the very least please add information about this to your FAQ! I suppose I could add a PR to the docs, but you probably know better how to phrase this in text so it fits with the rest of the FAQ tone.

**Comment by AdamBraden** [comment] 2024-08-20 22:57
@noopman - REFS support long file paths. See:
[https://learn.microsoft.com/en-us/windows-server/storage/refs/refs-overview#feature-comparison](https://learn.microsoft.com/en-us/windows-server/storage/refs/refs-overview#feature-comparison)

The problem is File Explorer does not, and that is the error you are seeing - it is in File Explorer itself. If you need to copy long file paths, recommend using robocopy.

@mattwojo - please close this issue.

**Closed as completed** 2024-08-27 19:00 UTC
Labels: Pri3
