### ISSUE TITLE
Upload a file via API and reading it from an app

### ISSUE THREAD

**Issue by kubakista** [MicrosoftDocs/windows-uwp#624] opened 2018-05-28 11:05 UTC
Hello,

I am facing some issue which seems to be present in OS versions: 10.0.17133.2020 and 10.0.17134.3036.

I upload a file via Xbox Device Portal (I use my browser to upload it) to the Temp folder of my app. Then I try to load and read my file from the application.

await ApplicationData.Current.TemporaryFolder.GetFileAsync("myfile")

It throws an error, "File does not exists". But the file is there. Also when I create a file from the app in Temp folder, I do not see it via API. OS version 10.0.16299.5101 looks like the last version where it works properly.

I tried to do the same on my laptop with Windows 10 and it works there without problems, even on build 17134.48. It seems like issue related only to Xbox.

Do you happen to know if something has changed?  
Thank you.

Best Regards,  
Jakub Krampl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1ab644-ee7d-3dec-cd0f-cbb1e4d8b6ac
* Version Independent ID: 97eecc36-8e2e-d4c7-1ecb-948e0846bda5
* Content: [Device Portal core API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by WilliamsJason** [comment] 2018-06-12 20:08
This looks like a regression with Xbox on those builds. We'll get a fix into internal builds but it might be a while before any previews with the fix.

Device Portal is showing the generic folder--what you get when you call TemporaryFolder.GetFileAsync from a Multi-user app instead of a single-user app--when it should be showing the user folder for whichever user you have signed in (which is the same user that your app is using when you call the API).

**Comment by eliotcowley** [comment] 2018-11-30 21:19
Hi @kubakista, thanks for the feedback. Sorry for the long wait. I'm testing this out now on Windows 10 build 17763, with SDK build 17763 as well. Here's what I've found:

* Uploading a file to the app's temp folder through the Windows Device Portal works, and I am able to read it from the app.
* I am able to create a file through the app to the app's temp folder.

I don't currently have an Xbox set up to test with, but I'm working on it. In the meantime, would you be able to test on an Xbox that's been updated to 17763, with an app that targets the 17763 SDK? It's possible that this has been fixed in the latest update.

**Comment by kubakista** [comment] 2018-11-30 21:44
Hi @eliotcowley,
it was already fixed in 17763 (build 2023).
In the latest build 3062 it works as well.

I guess this ticket can be closed.

**Comment by eliotcowley** [comment] 2018-11-30 23:56
Okay great, thanks for letting me know.

**Closed as completed by eliotcowley** 2018-11-30 23:56 UTC
