### ISSUE TITLE
Wrong Padding value in example

### ISSUE THREAD

**Issue by Gnitry** [MicrosoftDocs/windows-uwp#955] opened 2018-09-03 08:04 UTC
On the page [The Fluent Design System for Windows app creators](https://docs.microsoft.com/en-us/windows/uwp/design/fluent-design-system/index) we see in the example code `Padding="24,16"`, but on the image below it is `Padding="16,24"`

![image](https://user-images.githubusercontent.com/3641011/44974608-dc2a0100-af68-11e8-8d10-c6e23706347a.png)

**Comment by bartlannoeye** [comment] 2019-02-11 20:13
Duplicate of #1439, can be closed.

**Closed as completed** 2019-02-11 21:44 UTC
