### ISSUE TITLE
Cannot open precompiled header file: Continuation of issue 103

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/windows-uwp#1605] opened 2019-04-16 11:49 UTC
#103 has been archived so I can't query further on it. 
I am using C++/winRT as a UWP library. It was building fine. First I changed the name of pch.h to btwrpch.h (everywhere) and rebuilt. Changed the name in the properties 'precompiled headers' option and it still built fine.

Then I moved the btwrpch.h file to an include directory in my library project along with all the other header files for my classes. In my cpp files I replace "#include "pcwrpch.h" with "include/pcwrpch.h" and I got the above error. Then in the precompiled headers option I did the same. Same error. I have already set the properties additional include directories to the 'include' directory. Same error.

Why can't I move that header file into another directory? Is there something under the hood assuming that this file is always found at the project level?

**Comment by stevewhims** [comment] 2019-10-17 23:43
Hi, @brianreinhold. I'm really sorry for the long delay in responding, and thanks for filing this issue.

This sounds like a product support question about Visual Studio.

If you have feedback about documentation content, then you can click **Send feedback about** \> **This page** on the relevant topic. For product feedback in the context of a particular topic, you can instead click **Send feedback about** \> **This product**, and then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.

I'm sorry that I couldn't be of more immediate help with this issue.
-Steve

**Closed as completed by stevewhims** 2019-10-17 23:43 UTC
Labels: product-question
