### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by AdamRLukaitis** [MicrosoftDocs/windows-uwp#3309] opened 2021-08-19 04:49 UTC
This should read Windows 10, version 2004 instead of 20004

5. In the following dialog box, set the Target version to Windows 10, version 20004 (build 19041) and Minimum version to Windows 10, version 1809 (build 17763) and then click OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?tabs=desktop-cpp)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by stevewhims** [comment] 2022-02-24 05:34
Sorry for the delay in responding. The issue is fixed now.

-Steve

**Closed as completed by stevewhims** 2022-02-24 05:34 UTC
Labels: doc-bug, Pri2, reunion/prod, winui-conceptual/tech
