### ISSUE TITLE
Need help get my dour420 Microsoft back

### ISSUE THREAD

**Issue by Dour420** [MicrosoftDocs/windows-uwp#2752] opened 2020-10-13 16:15 UTC
Everything on my phone as Been a mess for months I final figure out what goin in there using my dour420 you guy let her changed the email and phone number as the 2 step gave me aaronconti@live.com as a promotional email and so I'm suck in that loop this email was never a separate account now I'm gettin my identity stole and government unemployment and cash assistance as well as any payment method on my phone including apps and direct deposit info is all being used by them they set up a pull that take all payment methods thank for entrainment for months but let's do somethjng as i write this apple is monitoring my email and account on my phoneand had locked a couple of them now let's see Microsoft take this seriously as the and not doin anything for education purposes and I never agree nor am I ok with what's goin on it's my account it's not far what has been slipping thru the cracks I been being robbed for months there break numerous terms and agreement on GitHub and are able to read and right to impersonate me thanks you!!!!

**Comment by hkhmsft** [comment] 2020-10-17 01:04
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed about the documentation.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

**Closed as completed by hkhmsft** 2020-10-17 01:04 UTC
Labels: support-request, Pri3

**Comment by Dour420** [comment] 2020-10-17 02:01
Yes now I have access to it and they made another one on top of it and I’m locked out of that one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
