### ISSUE TITLE
cppwinrt example 

### ISSUE THREAD

**Issue by Dylan-H** [MicrosoftDocs/windows-uwp#1347] opened 2018-12-28 08:28 UTC
https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-attached-properties#code-example
bool IsMovable()     -----&gt;   the accessors must be named GetIsMovable and SetIsMovable ?
 Windows::UI::Xaml::DependencyProperty IsMovableProperty(){ return m_IsMovableProperty; }      not static ?

 winrt::xaml_typename&lt;bool&gt;()  ------&gt;  T must be WinRT type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369c139c-69a6-8817-5cb2-6e93d64d8cce
* Version Independent ID: 6feed647-1cd1-8971-eb36-f14aaccad151
* Content: [Custom attached properties - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-attached-properties#code-example)
* Content Source: [windows-apps-src/xaml-platform/custom-attached-properties.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/custom-attached-properties.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment] 2019-01-04 03:55
Hi, @Dylan-H, yes, the content and code is correct. For example, about the naming convention for accessors, and the actual DP getter is not static, by design. bool is a Windows Runtime type, in that it can be passed across the application binary interface (ABI). Please let me know if this doesn't address your questions. I'll leave the issue open for a while. ~Steve

**Comment by Dylan-H** [comment] 2019-01-04 05:19
@stevewhims   
Sorry, my English is not very good. I'm using translation software.
Without Set (Get), I can't access DP as shown in the example above. In my code, I have to write SetIsMovable (GettIsMovable) to work properly.
winrt::xaml_typename<bool>() ------> “T must be WinRT type” is a static_assert  error.
winrt code:
    template <typename T>
    inline Windows::UI::Xaml::Interop::TypeName xaml_typename()
    {
        static_assert(impl::has_category_v<T>, "T must be WinRT type.");
        static const Windows::UI::Xaml::Interop::TypeName name{ hstring{ impl::xaml_typename_name<T>::value() }, impl::xaml_typename_kind<T>::value };
        return name;
    }
 and I can only write it like this   ------>
{ winrt::hstring(winrt::name_of< bool>()) ,Interop::TypeKind::Primitive }

**Comment by stevewhims** [comment] 2019-01-05 02:28
Hi, @Dylan-H, there actually IS a problem with the code example, so I'm taking a closer look. The problem is that the code is showing a regular dependency property instead of an attached property. However, I can confirm that the expression winrt::xaml_typename<bool>() is correct. Bool is a WinRT type. Anyway, I hope to have more news for you tomorrow when I've worked on this. Thanks for bringing the issue to my attention. ~Steve

**Comment by stevewhims** [comment] 2019-01-07 23:54
@Dylan-H, I've fixed the code example now, and confirmed that it builds and runs as expected on the latest public versions of the Windows SDK, Visual Studio, and Windows. Now that I've fixed the topic, I'll address your specific points/questions.

Yes, the accessors must be named GetIsMovable and SetIsMovable. Currently, you can't use those from XAML markup, but you can use them in imperative code (and the topic now shows how to do that). The property should be static, you're right (this is an attached property), and I've fixed that in the topic's code. And lastly, to reiterate my earlier confirmation, the expression `winrt::xaml_typename<bool>()` is correct and I would NOT expect it to give a compile error. Bool is a WinRT type.

Please let me know whether this has been useful, and if so then we can close the issue.

Thanks!
Steve

**Comment by Dylan-H** [comment] 2019-01-09 12:39
@stevewhims  Sorry，    winrt::xaml_typename<bool>() is correct  
“T must be WinRT type”  from other code
Thanks!

**Closed as completed** 2019-01-09 12:39 UTC

**Comment by stevewhims** [comment] 2019-01-09 22:27
Sounds good, thanks! :)
