### ISSUE TITLE
Where's ColdFusion?

### ISSUE THREAD

**Issue by RHMason** [MicrosoftDocs/windows-uwp#2612] opened 2020-07-29 21:22 UTC
[Enter feedback here]

Didn't see ColdFusion (Lucee on open source) on your list of languages.  ColdFusion was important enough that Bill Gates made two attempts to buy the company.  Unique among languages CF'ers are running the highest percentage of Windows servers as well as developing on Windows machines.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7779352b-7b4e-dad8-7c1b-b9aba2c5e561
* Version Independent ID: a5b81b80-87a1-b6e2-8936-baf6c1a0b9c5
* Content: [Set up your development environment on Windows 10](https://docs.microsoft.com/en-us/windows/dev-environment/overview)
* Content Source: [hub/dev-environment/overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/overview.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by bitcrazed** [comment] 2020-08-27 17:50
@RHMason - thanks for the suggestion. As someone who dabbled with Cold Fusion back in 1998-2000, I am delighted to see it's continued to evolve and develop over the last 25 years!

Could we ask if you have any favorite CF resources, sites, videos, etc. that you particularly recommend? We'd be happy to incorporate your (and others') suggestions into a guide for CFML developers on Windows!

**Comment by mattwojo** [comment] 2020-08-28 19:01
Thanks for filing this issue @RHMason . I'm closing as we're trying to clean up and prioritize our list of issues, but I would still echo Rich in asking whether you have any favoriate resources or suggestions for what you would like to see covered in a Cold Fusion guide. I will continue to receive any responses even though the issue is closed and it can be reopened if needed for further discussion. 
Thanks again!

**Closed as completed by mattwojo** 2020-08-28 19:01 UTC
Labels: product-feedback, windows-nodejs/tech, dev-environment/prod, Pri2

**Comment by bitcrazed** [comment] 2020-08-28 22:42
General etiquette says that we don’t close issues on things we plan to deliver until we deliver them, otherwise it’s a bit of a mixed-message 😉

Instead, might want to create a series of tags to say “status-planning” or “status-queued” or similar?

**Comment by RHMason** [comment] 2020-09-07 05:10
Rich and Matt,

Apologize for the delayed reply.  I am solo building a startup and have
been heads down in code all day, every day.

Here's a few resources I've put together this evening.  If I were to reach
out to the community they would undoubtedly supply many more.  I am
probably leaving out many important ones.

CF Slack community – http://cfml.slack.com
Adobe CF community -
https://community.adobe.com/t5/coldfusion/bd-p/coldfusion?page=1&sort=latest_replies&filter=all
Adobe CF site – http://www.coldfusion.com
Lucee Organization – http://lucee.org
Lucee CFML site – http://www.lucee.com
Learn CF in a week - http://learncfinaweek.com/
CF blogs - https://coldfusionbloggers.org/
Community created CF docs  http://cfdocs.org
Community OS functions – http://www.cflib.org
Awesome ColdFusion - https://github.com/seancoyne/awesome-coldfusion

Frameworks

ColdBox (Laravel style organization) – http://coldbox.org
FW/1  -  http://framework-one.github.io/
CF Wheels (Ruby on Rails like) - https://cfwheels.org/
Taffy (Rest) - https://taffy.io/

Conferences

Adobe CF Summit - https://cfsummit.adobeevents.com/
CF Camp (Lucee in Europe) – https://www.cfcamp.org/
Into the box (ColdBox) - https://www.intothebox.org/

Notable bloggers

Ben Nadel - https://www.bennadel.com/blog/recent-blog-entries.htm
Pete Freitag - https://www.petefreitag.com/
Mathew J. Clemente - https://blog.mattclemente.com/
James Moberg - https://dev.to/gamesover/
Steven Neiland - http://www.neiland.net/blog/
Charlie Arehart - http://www.carehart.org/blog/client/index.cfm
Brian Klaas - https://brianklaas.net/
Will Genovese - https://www.trunkful.com/

Rick

**Comment by bitcrazed** [comment] 2020-09-14 20:10
Thanks for sharing these great resources with us Rick. We'll definitely incorporate these and others when we get to CF content.
