### ISSUE TITLE
How To Debug PushNotificationTrigger in Visual Studio

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/windows-uwp#858] opened 2018-07-31 21:37 UTC
This can be done using VS's "Debug Installed App Package" option. Select your app, then select "Do not launch but debug my code when it starts". This done, fire a Push notification from your service and you can then debug your code. (Other difficult-to-debug triggers may also work with this but I have only tried Push).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a01b34-9cc4-f79e-70c2-4082364ef213
* Version Independent ID: ae8347fc-6943-25e4-a5d9-1cb1c8920d8e
* Content: [Debug a background task - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/debug-a-background-task)
* Content Source: [windows-apps-src/launch-resume/debug-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/debug-a-background-task.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stevewhims** [comment] 2018-09-24 20:11
Hi, @amp64, thank you for filing this issue, and sorry for the delay in getting back to you. I've kicked off an internal workstream around this content suggestion. Once that workstream is confirmed, if/when I get the go-ahead, I'll update this topic.

For now, I'll go ahead and close this GitHub issue, since the work is being tracked internally now.

Thanks again!
~Steve

**Closed as completed by stevewhims** 2018-09-24 20:11 UTC
