### ISSUE TITLE
DisplayTimestamp breaks Toasts on Xbox

### ISSUE THREAD

**Issue by veleek** [MicrosoftDocs/windows-uwp#446] opened 2018-04-13 06:28 UTC
It looks like specifying a DisplayTimestamp causes the Toast notification to never show up.  Is this expected for some reason on the Xbox, or is there a platform bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e46be9-840b-4a6b-59b4-cee8e1cd11a7
* Version Independent ID: 2d445059-0138-8cc3-9642-2b79e582580a
* Content: [Custom timestamps on toasts - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/custom-timestamps-on-toasts#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/custom-timestamps-on-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/custom-timestamps-on-toasts.md)
* Service: **unspecified**
* GitHub Login: @anbare
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment] 2018-04-13 14:24
Hey veleek, thanks for reporting this! It definitely shouldn't cause the toast to not display.

@veleek can you provide the final XML of the toast you're sending to the Xbox?

**Comment by veleek** [comment] 2018-04-14 07:55
Slightly modified from the example documentation:

The following XML properly pops a toast:
```xml
<?xml version="1.0" encoding="utf-8"?>
<toast launch="action=viewConversation&amp;conversationId=384928">
    <visual>
        <binding template="ToastGeneric">
            <text>Andrew sent you a picture</text>
            <text>Check this out, Happy Canyon in Utah!</text>
            <image src="https://picsum.photos/364/180?image=1043" placement="hero" />
            <image src="ms-appx:///leaf.jpg" placement="appLogoOverride" hint-crop="none" />
        </binding>
    </visual>
</toast>
```

The following XML does NOT pop a toast:
```xml
<?xml version="1.0" encoding="utf-8"?>
<toast launch="action=viewConversation&amp;conversationId=384928" displayTimestamp="2018-04-14T00:35:32.301-07:00">
    <visual>
        <binding template="ToastGeneric">
            <text>Andrew sent you a picture</text>
            <text>Check this out, Happy Canyon in Utah!</text>
            <image src="https://picsum.photos/364/180?image=1043" placement="hero" />
            <image src="ms-appx:///leaf.jpg" placement="appLogoOverride" hint-crop="none" />
        </binding>
    </visual>
</toast>
```

I tried multiple different values for `displayTimestamp` including `DateTimeOffset.UtcNow`, `DateTime.UtcNow`, `DateTimeOffset.Now`, `DateTimeOffset.Now.AddSeconds(-3)`, among others.  The only thing that pops a toast is when displayTimestamp is set to null.  

All of the values I tested properly toasted on a PC.

**Comment by andrewleader** [comment] 2018-04-18 17:33
Thanks veleek for the excellent repro steps, we're investigating it!

**Comment by andrewleader** [comment] 2018-04-30 17:04
Hey @veleek, we've investigated the issue and have found the cause. It's a bug that will require an OS update to fix. Our team is looking into a fix, but we can't talk timelines at this point yet.

For now, you'll just have to modify your toast on Xbox and not including displayTimestamp. DisplayTimestamp simply isn't supported and will break on Xbox until that bug is fixed.

**Comment by ginami** [comment] 2018-08-14 16:17
Closing this issue for now...thank you!

**Closed as completed by ginami** 2018-08-14 16:17 UTC

**Comment by Carrie3563** [comment] 2018-08-18 23:03
my SharePoint replies someone else SharePoint instead of mine
