### ISSUE TITLE
How can I use XAML controls made by C++/WinRT from C# (as WinUI3)?

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/windows-uwp#4013] opened 2022-08-25 01:30 UTC
How can I consume XAML controls made by C++/WinRT from C# (as WinUI3)?
I think it can in UWP project but can not find out how in Windows App SDK. project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a199ae-561b-98b6-8cf0-101aedbfe599
* Version Independent ID: a8091c04-868d-51aa-f4d1-207c5c795235
* Content: [XAML custom (templated) controls with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/xaml-cust-ctrl)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-08-25 22:00
Hi, @vmx17.

For a UWP project I believe you'd create a C++ WRC (see [Windows Runtime components with C++/WinRT](https://docs.microsoft.com/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt)). You'd implement a subclass of Windows.UI.Xaml.Controls.Control. And then consume that WRC from a C# app. There was a time in the past when you couldn't use XAML types in a WRC, but I believe you can these days.

Now, for WinUI 3 (and the Windows App SDK), I would begin by investigating whether you can do the same thing. WinUI 3 types are Windows Runtime types (even though they're not UWP types). So I would try creating a C++ WRC, but implement a subclass of Microsoft.UI.Xaml.Controls.Control (instead of Windows.Xxx). I haven't tried that, so I don't know whether it works. And this topic is for UWP apps. But the above is what I'd try first.

If you run into any issues, you could try the following resources:

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll close this issue, since there's nothing to update in the docs, and this feedback channel is for reporting problems with the topic.

I'm sorry I couldn't help further.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-08-25 22:00 UTC
Labels: uwp/prod, platform/tech, Pri2
