### ISSUE TITLE
UserActivity.CreateSession refuses to finish

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#1808] opened 2019-07-19 01:53 UTC
The User Activity (Timeline) feature doesn't work. I tried debugging the code and found out UserActivity.CreateSession() cannot finish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf5f88c-d598-d624-a570-9a93d2092cf2
* Version Independent ID: 6f9b95e7-0d1a-6b88-cde0-ba4b60dcbced
* Content: [Add Windows 10 user activities and notifications - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-4)
* Content Source: [hub/apps/desktop/modernize/modernize-wpf-tutorial-4.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/modernize-wpf-tutorial-4.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2019-07-19 16:47
I'm sorry you're encountering this issue. I just stepped through the walkthrough again and confirmed that this section is working as expected for me: UserActivity.CreateSession() completes without error and the expenses I view in the sample app show up in my Timeline view. Have you tried going through the steps in this section yet to see if you missed a step? If you try running the code without debugging, what happens when you view an expense - do you get an exception, etc.?

**Comment by mcleanbyron** [comment] 2019-07-19 23:10
Since this doesn't appear to be an issue with the article at this time, I'm closing this issue for now. Please feel free to reopen with more info as needed. Thanks!

**Closed as completed by mcleanbyron** 2019-07-19 23:10 UTC

**Comment by dongle-the-gadget** [comment] 2019-07-20 01:40
Thanks, I tried Start without Debugging and then everything works as expected.
