### ISSUE TITLE
I can't get subscriptions for a user

### ISSUE THREAD

**Issue by poumason** [MicrosoftDocs/windows-uwp#649] opened 2018-06-06 17:09 UTC
I reference the [Get subscriptions for a user](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-subscriptions-for-a-user ) to confirm user has subscription.

But I always got the `{ "items": [] }`

I also try use [Query for products](https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products) to query user own products. 

I also got the same response.

I don't why.

**Comment by mcleanbyron** [comment] 2018-06-06 20:16
I'm sorry you're running into troubles using this API. I'm going to close this issue because it appears you have already reached out to an internal MVP alias for help, and that is a more appropriate resource for help (Issues in this repo are intended primarily for feedback/problems with the docs rather than product support). 

That said, some things to troubleshoot/consider: 
- Is it possible that the user specified by the Microsoft Store ID key you passed to the _b2bKey_ parameter doesn't have any subscription entitlements for any of the products assigned to your Dev Center account? 
- Are you receiving any HTTP error codes with the response?

**Closed as completed by mcleanbyron** 2018-06-06 20:16 UTC

**Comment by poumason** [comment] 2018-06-07 01:37
I sure the MS Store ID has a subscription.
Because I use StoreContext.GetAppLicenseAsync method and got the purchased StoreProduct.
I also find the purchased order on the https://account.microsoft.com/billing/orders .

So I don't what happend.

By the way, If I use https://onestore.microsoft.com to generate AAD access token, I invoke collections API or purchase APIs don't response HTTP error codes.

But I follow the [link](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-3-create-azure-ad-access-tokens) :
- I use https://onestore.microsoft.com/b2b/keys/create/collections to get access token to  invoke collection APIs , and I got un-authorization error.
- https://onestore.microsoft.com/b2b/keys/create/purchas , it is also response un-authorization.

finally, I always use https://onestore.microsoft.com to generate AAD access token and invoke collection APIs and purchased APIs. 

I send the internal MVP email, but I don't receive any response.  ha

**Comment by mcleanbyron** [comment] 2018-06-07 16:29
If you're getting an unauthorization error/message when trying to generate an access token with the https://onestore.microsoft.com/b2b/keys/create/collections or https://onestore.microsoft.com/b2b/keys/create/purchase audience URIs, that's a likely source of your problem, since you need to successfully create that token in order to generate the valid Microsoft Store ID key for the current app customer. Can you confirm that you have performed all the tasks in [step 1](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-1-configure-an-application-in-azure-ad) and [step 2](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-2-associate-your-azure-ad-application-id-with-your-app-in-windows-dev-center)? 

I do see a reply to you on the MVP alias asking you for cabs and other data. I'll forward it directly to you to make sure you see it. In your response, please also provide specific details about the "unauthorization" message you are seeing when trying to create the tokens.

**Comment by poumason** [comment] 2018-06-08 09:17
Thank your response.
"unauthorization" issue already be solved. 
Because I don't notice things:

- in http request: AAD access token must be built from https://onestore.microsoft.com
- built MS Store ID must be depended API type: collection or purchases

I follow the rule to solve it.

And now, I already got the purchases and collections of the user.
But I sure got `{ "items": [] }` result is difference with "unauthorization".
Because the same code always got `{ "items": [] }`, today the same code got the result. haha...

**Comment by mikejd** [comment] 2018-08-19 10:41
Hi there,

We experience the same issue, always getting `{ "items": [] }` when requesting subscriptions for a user. @poumason, could please confirm that you resolved this problem and successfully get list of subscriptions?

I believe that we followed the [docs](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service) closely and here is what we did:

1. Created new app registration in Azure Active Directory.
2. Associated identifier of the app registration (created in the first step) with our app Windows Dev Center Dashboard (this required Global administrator permission, which wasn't immediately obvious).
3. Created three AAD access tokens for different audience URIs (general, purchases and collections).
4. Created Microsoft Store ID keys for Collection and Purchase APIs by calling `StoreContext.GetCustomerCollectionsIdAsync` and `StoreContext.GetCustomerPurchaseIdAsync` respectively.
5. Finally we called Collections and Purchases API to request products / subscriptions for the user (using Microsoft Store ID keys, generated in step 4). Response is "200 OK", but the list is always empty and that is the major blocking issue right now.

We just confirmed via https://account.microsoft.com/billing/orders that our test Microsoft account (who we created Microsoft Store ID Keys on behalf of) owns one durable purchase and one active subscription. 

So why do we still get empty lists?
