### ISSUE TITLE
trying to find method of offering volume pricing for a dev app in the app store

### ISSUE THREAD

**Issue by juliankauai** [MicrosoftDocs/windows-uwp#4195] opened 2022-12-13 06:18 UTC
in this page, 
https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/price-and-availability?pivots=store-installer-msix#organizational-licensing

under, 'Organizational licensing' is a very important link titled.'[Organizational licensing options](https://learn.microsoft.com/en-us/uwp/publish/organizational-licensing).

which get's a 404-content not found. this is so common in ms documentation that i'm surprised there isn't a tool that reports this to a person whose job it is to fix that sort of thing.

i'm honestly shocked at the quality of the pages. this isn't hyperbole. we've just spent months trying to get an app in the store and it's just my real feedback.

thanks for having a feedback link.

julikan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2d5e61b-9914-b516-c450-2d97550bd880
* Version Independent ID: e2d5e61b-9914-b516-c450-2d97550bd880
* Content: [Set app pricing and availability - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/price-and-availability?pivots=store-installer-msix#organizational-licensing)
* Content Source: [hub/apps/publish/publish-your-app/price-and-availability.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/price-and-availability.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment] 2023-03-13 22:52
Dupe of [4220](https://github.com/MicrosoftDocs/windows-dev-docs/issues/4220).

Resolution there was that the link was broken during a phased series of moving docs within our repo. Some links were temporarily broken during that process, but are working now.

The page you were looking for is [Organizational licensing options](https://learn.microsoft.com/en-us//windows/apps/publish/organizational-licensing)

**Closed as completed by hickeys** 2023-03-13 22:52 UTC
Labels: apps/tech, Pri2, reunion/prod
