### ISSUE TITLE
question about binding display name to ms-resource:

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3850] opened 2022-05-25 05:39 UTC
hi MSFT 
   If not exist support language resource string in binding display name for start menu, 
   then OS changed  what the title way to show ?
   
   ex:
   my UWP only has "CustomTitle" of en-US / Jp / cht / chs, OS locate which change to  hi(Hindī).
   I found that will keep pervious display title name at start menu. 
   Does it meet expectations?

   if so, how I set default title in not support language with "ms-resource:CustomTitle" 
   programmably ?

https://imgur.com/a/UoyUcw7

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 918121d4-2ab4-e3fd-a464-45d4ef407319
* Version Independent ID: a0bf9b8b-b8a3-fa41-d54f-fb633033b22f
* Content: [Understand user profile languages and app manifest languages - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/globalizing/manage-language-and-region)
* Content Source: [hub/apps/design/globalizing/manage-language-and-region.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/globalizing/manage-language-and-region.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment] 2022-10-28 17:33
Hi @jeremyLn - looks like your question was answered in https://learn.microsoft.com/en-us/answers/questions/870450/uwp-binding-display-name-to-ms-resource.html. Closing this issue.

For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).

For completeness, here are a few more developer support resources.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Closed as completed by Karl-Bridge-Microsoft** 2022-10-28 17:33 UTC
Labels: product-question, design/tech, Pri2, reunion/prod
