### ISSUE TITLE
Getting a 200 when getting a user's subscriptions, but a 401 when granting free products

### ISSUE THREAD

**Issue by benjaminfox** [MicrosoftDocs/windows-uwp#903] opened 2018-08-14 04:34 UTC
My token generation seems to be working fine - I can successfully query for a user's subscriptions, but the same token set gets a 401 when trying to grant a free product. A bit more detail here: https://stackoverflow.com/questions/51830079/why-is-my-azure-ad-application-not-authorized-to-grant-free-products

Is there anything more to say in this documentation about permissions, etc. that are required to allow a service to work with all the documented endpoints?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bdee9e-2095-4423-62c5-0beb5520dfd3
* Version Independent ID: fad19d6f-2fa3-ff54-925a-020fe65cadbc
* Content: [Manage product entitlements from a service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2018-08-20 19:22
I'm sorry you encountered this problem. This problem was apparently caused by a service-side bug that was fixed last week, so I am closing this GitHub issue.

**Closed as completed by mcleanbyron** 2018-08-20 19:22 UTC

**Comment by benjaminfox** [comment] 2018-08-21 19:34
That's great news, confirmed that it looks like it's working on my end. Thanks very much for looking into it.
