### ISSUE TITLE
MIDI API Problems

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/windows-uwp#892] opened 2018-08-10 21:13 UTC
It's worth pointing out that there are currently two crippling problems with MIDI in UWP.
Both problems are discussed in the thread [WinRT MIDI stack name handling flaw. WinRT MIDI stack is presently unusable.](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/e956555c-0640-4531-9beb-cba48a847020/winrt-midi-stack-name-handling-flaw-winrt-midi-stack-is-presently-unusable)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by EddieLotter** [comment] 2018-11-18 21:52
It appears that update 1809 fixes these issues.
Can anyone confirm?

**Comment by parkovski** [comment] 2018-12-13 04:35
Hi, I was linked here by [this reddit thread](https://www.reddit.com/r/Windows10/comments/a5b81m/any_hope_for_uwp_midi_apis/). I'm still having naming issues as I wrote in that thread. Can't speak for sysex as I don't plan to pursue this API further until I can get correct names from it.

**Comment by IgorX2** [comment] 2019-01-28 17:37
Doesn't work on any platform. Using `MidiInPort` and input messages anywhere in the app will cause the app to hang on exit.

**Comment by EddieLotter** [comment] 2019-01-28 19:28
@IgorX2 I am not experiencing an app hang on exit after sending and receiving messages.
What MIDI device do you have connected to your MIDI In port?

**Comment by IgorX2** [comment] 2019-02-02 08:27
@EddieLotter I have found that moving the destructor logic to the Suspend method circumvents the problem. However, if the MIDI device is disconnected during app's execution, the problem occurs regardless of the workaround.

The MIDI device is M-Audio 88es Keyboard and the sound card is M-Audio FastTrack.

**Comment by drewbatgit** [comment] 2020-07-24 18:23
Issues in this repo are intended specifically for fixes to the documentation, not for reporting or tracking product bugs or developer support requests. As this discussion seems related to technical issues in the product, I am going to close the issue to get it out of the documentation queue. If there is a resolution/workaround to this issue that you think should be included in the documentation, feel free to comment here, even though the status of the issue is "Closed". Thanks!

**Closed as completed by drewbatgit** 2020-07-24 18:23 UTC
Labels: product-feedback, windows/prod, Pri2
