### ISSUE TITLE
Default Add-AppxPackage Installer can provide an invalid winget source list

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/windows-uwp#4646] opened 2023-10-01 04:26 UTC
Hey Team, I'm not sure how far reaching this issue may be, but I've seen this as a problem with 2 specific Windows 11 22H2 AVD SKU's within Azure recently after you first deploy a VM and try to use the following command:

```Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe```

Image Plans Affected in Azure:
- win11-22h2-avd (Multi-Session: Did not have AppInstaller by default)  
- win11-22h2-ent (Single-Session: Did have AppInstaller by default)

Once AppInstaller is verified to be installed from the Base O/S, when you do a ```winget source list```, you see this on the list:

```https://winget.azureedge.net/cache```

When attempting to install an app via winget with that source, it will fail.  It should be ```https://cdn.winget.microsoft.com/cache```.   Workaround is either remove that source/add the correct one or I've had to download and install winget directly from GitHub and that seemed to work:

```powershell
# Downloads and installs Winget
$URI = "https://aka.ms/getwinget"
$Installer = "$env:SystemDrive\packages\Microsoft.DesktopInstaller.msixbundle"
Invoke-WebRequest -Uri $URI -OutFile $Installer
Add-AppxPackage $Installer
```
I don't know if this is a code/bug defect in certain images or Windows 11 22H2 itself.  Thought it would be worth sharing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by denelon** [comment] 2023-10-03 20:52
We're working on CDN migration:
* https://github.com/microsoft/winget-cli/issues/3652

If App Installer (delivery vehicle for WinGet) is updated, the newer client versions use the https://cdn.winget.microsoft.com/ URL.

One way to do this is to run `winget install "App Installer" -s msstore --force` after the initial registration. The "msstore" source URL isn't affected by the CDN migration work in progress.

**Comment by mattwojo** [comment] 2023-10-03 21:44
Hey @brmcmill - Could you let me know if @denelon's suggestion to update the App Installer / WinGet version addresses the issue you're encountering when using WinGet with a Windows VM in Azure? This sounds like something that should be included in the docs at least until the issue is resolved.

**Comment by brmcmill** [comment] 2023-10-03 21:56
Hey @denelon / @mattwojo  -- thank you for the info, I was not aware of the CDN changes!  That method will work too.  Some customers disable the MS Store for various reasons, so it may not always be an option.

**Comment by brmcmill** [comment] 2023-10-03 22:55
I tested the store cmdline out, but it did not update the source list.  Did not find it, guessing unless you have a Store Account with the one you're using.

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/26752719/1b59ec54-7a19-464a-a04e-3e7f4d4ed450)

**Comment by denelon** [comment] 2023-10-04 15:10
@brmcmill, that looks like an older version of WinGet.
We've recently added support for dependencies in WinGet, and have been considering adding the stable releases of WinGet to the community repository to support WinGet being able to update itself.

Your solution to grab the latest package appears to be a reasonable solution to the problem as it stands today.

**Comment by mattwojo** [comment] 2024-03-08 20:19
It sounds like this issue is related to versioning and doesn't require an update to the WinGet docs at this time, so closing this issue. If you find this not to be the case, please re-open this issue so that we can get the documentation appropriately updated. Thanks again for contributing to the quality of our docs!

**Closed as completed by mattwojo** 2024-03-08 20:19 UTC
Labels: dev-environment/prod, Pri1, package-manager/tech
