### ISSUE TITLE
version info seems wrong

### ISSUE THREAD

**Issue by SharPad** [MicrosoftDocs/windows-uwp#907] opened 2018-08-15 01:32 UTC
Testing for API exists (ApiInformation.IsTypePresent) returns false for RS1 and RS2. Supported only on 16299 and above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291dc819-9b43-818a-f839-f69d0a0b432e
* Version Independent ID: d6cfeb3b-dd87-e0df-95a2-8b1d282f24a3
* Content: [Request ratings and reviews for your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/request-ratings-and-reviews)
* Content Source: [windows-apps-src/monetize/request-ratings-and-reviews.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/request-ratings-and-reviews.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2018-08-20 19:56
Thanks for reporting this. I have confirmed that the [SendRequestAsync](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storerequesthelper.sendrequestasync) method was added to the UWP platform in Windows 10 version 10.0.14393.0 (this is also referred to as version 1607 or Anniversary Edition). 

To be clear, are you saying that in your testing IsTypePresent returns false for this method on anything earlier than v10.0.16299?

**Comment by SharPad** [comment] 2018-08-21 02:52
The results are not very conclusive but even though IsMethodPresent returns true on 14393 and 15063 builds, calling the method seems to throw an exception. It is likely flavor dependent. RS1 and RS2 Pro and Home seem to fail. But Enterprise works. RS3 Home failed first time but then on trying again it was able to show the store login.  Will try to write a sample program to test this feature independently.

**Comment by mcleanbyron** [comment] 2018-11-19 22:24
Because this does not appear to be a problem with the docs, I am closing this issue for now. If you continue to encounter problems calling this method on Windows 10 version version 1607 or later, please contact [developer support](https://developer.microsoft.com/windows/support).

**Closed as completed by mcleanbyron** 2018-11-19 22:24 UTC
