### ISSUE TITLE
Question: How can I refer to C++/WinRT XAML UserControl from C#?

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/windows-uwp#4028] opened 2022-09-02 08:28 UTC
Hi!
I'm trying to add a _SwapChainPanel_-based XAML UserControl WRC the code on this docs but have reference error saying;
_"Error WMC0001 Unknown type 'BoxRenderer' in XML namespace 'using:SimpleMathProjection' StubWinUI3Desktop E:\Codes\gitlab.example.com\NetProjection\StubWinUI3Desktop\DxPage.xaml 12 "_
To make the code attached, I referred to the page [below](https://docs.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component) and [others](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3) [pages](https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop?source=recommendations). In total, I think this place is the most adequate space to ask these things but if not, please show me where the best asking place.
The UserControl is just the cover of WinUI3 _SwapChainPanel_ named _BoxRenderer_. Though I intend to use C++ DirectX on there but currently no functions exist.

In short, please look in the archive;
1) build _CppWinRTComponentProjectionSample.sln_ --> this makes NuGet package
2) build _StubWinUI3Desktop.sln_ --> this makes the error above.
Detailed repro step is in Readme.md included in the archive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Version Independent ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Content: [Generate a C# projection from a C++/WinRT component, distribute as a NuGet for .NET apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**
[CppWinRTComponentProjectionSample.zip](https://github.com/MicrosoftDocs/windows-uwp/files/9476142/CppWinRTComponentProjectionSample.zip)

**Comment by stevewhims** [comment] 2022-09-02 19:59
Hi, @vmx17, and thanks for filing this issue.

For the [DirectX and XAML interop](https://docs.microsoft.com/windows/uwp/gaming/directx-and-xaml-interop?source=recommendations) topic&mdash;that topic is currently for UWP apps; I haven't tried that yet for a WinUI 3 app. At least one of the other two topics you're following is for WinIU 3, as you know. But your scenario feels a little like a combination of things that we don't have specific documentation about yet. So I would recommend asking on Microsoft Q&A.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

As you know, the feedback channel you used here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete. For questions (or requests for help) regarding a specific scenario, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all).

It seems like there's nothing specifically wrong with this topic as written. So I'll go ahead and close the issue.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-09-02 19:59 UTC
Labels: apps/tech, Pri2, reunion/prod

**Comment by vmx17** [comment] 2022-09-03 07:53
Rojer, Thanks!
This asking was moved to:
https://docs.microsoft.com/en-us/answers/questions/992490/how-to-make-projection-usercontrol-xaml-resource-i.html
(sorry for re-closing, @stevewhims)
