### ISSUE TITLE
Ambigram on the typography page is misspelled

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/windows-uwp#3187] opened 2021-06-24 19:51 UTC
The ambigram screenshot on "Typography in Windows 11" reads "The quick brown fox jumped over the lazy dog"---it should be "The quick brown fox jump**s** over the lazy dog."

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94d411c-212f-d301-5ed2-4b5cb3e9b897
* Version Independent ID: bc4d9a15-03d1-cbc4-1dff-0d44dd1c2b35
* Content: [Typography in Windows 11 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/typography)
* Content Source: [hub/apps/design/signature-experiences/typography.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/signature-experiences/typography.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment] 2021-08-27 18:52
Duplicate of [3200](https://github.com/MicrosoftDocs/windows-uwp/issues/3200)

**Closed as completed by hickeys** 2021-08-27 18:52 UTC
Labels: doc-bug, uwp/prod, apps/tech, Pri1
