### ISSUE TITLE
launchSettings.json is incorrect for VS2022

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#3378] opened 2021-09-30 18:59 UTC
The launchsettings.json described doesn't work in VS2022.
Instead it should just be this:
```json
{
  "profiles": {
    "single-project": {
      "commandName": "MsixPackage"
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0401c948-1dda-c819-ee88-902ac6fcbbd9
* Version Independent ID: c1748244-0f46-8dec-a88e-020f12d9a387
* Content: [Package your app using single-project MSIX - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp)
* Content Source: [hub/apps/windows-app-sdk/single-project-msix.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/single-project-msix.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2021-10-01 00:31
Hi @dotMorten - An engineer on the Windows team reviewed these instructions again and confirmed that the launchSettings.json contents in the article are working for them with Visual Studio 2022 + Windows App SDK Preview 1 extension + single-project MSIX extension.

Can you provide more details about the error you're encountering that renders the documented launchSettings.json contents unusable?

**Comment by mcleanbyron** [comment] 2021-10-11 22:33
We're closing this issue due to the lack of reply. If you have more details you can provide about the error that would help our engineering team reproduce and diagnose the error, please reopen with the details. Thank you.

**Closed as completed by mcleanbyron** 2021-10-11 22:33 UTC
Labels: support-request, /tech, reunion/prod
