### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by FeliciaAnnKelleyTaylorGV** [MicrosoftDocs/windows-uwp#4916] opened 2024-03-19 10:51 UTC
### Type of issue

Code doesn't work

### Feedback

gives to aim to store

### Page URL

https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#alias

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-extensions.md

### Author

@stevewhims

### Document Id

5f59e641-6576-e10e-99c0-794907285580

**Comment by stevewhims** [comment] 2024-08-02 21:49
Hi, @FeliciaAnnKelleyTaylorGV, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

But this particular issue doesn't feel like it's saying that something needs changing in the docs.

For questions (or requests for help) regarding a specific scenario, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation.

Thanks!
-Steve

**Closed as completed by stevewhims** 2024-08-02 21:49 UTC
Labels: Pri3
