### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by js1057662** [MicrosoftDocs/windows-uwp#4156] opened 2022-11-18 07:42 UTC
The documentation for Fancy Zones is out of date as of at least 11 / 18 / 2022. Creating and editing zones is now quite different from what the documentation explains.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by SeraphimaZykova** [comment] 2022-11-23 15:25
I'll look into it.

**Comment by Jay-o-Way** [comment] 2023-03-01 16:11
@js1057662 and @SeraphimaZykova There was a PR merged back in december. Is this issue still valid nowadays?

**Comment by SeraphimaZykova** [comment] 2023-03-01 16:21
> @js1057662 and @SeraphimaZykova There was a PR merged back in december. Is this issue still valid nowadays?

I believe the issue is no longer relevant.

**Comment by mattwojo** [comment] 2023-03-01 23:11
> > @js1057662 and @SeraphimaZykova There was a PR merged back in december. Is this issue still valid nowadays?
> 
> I believe the issue is no longer relevant.

Closing. Please re-open if it seems that there is an update needed to the FancyZones docs.

**Closed as completed by mattwojo** 2023-03-01 23:11 UTC
Labels: dev-environment/prod, Pri1, powertoys/tech
