### ISSUE TITLE
C++/WinRT projections on API docs are not working as this page says they should

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/windows-uwp#2401] opened 2020-04-28 23:49 UTC
This page says:

&gt; Below is the syntax block taken from the documentation topic for [RoutedEventHandler](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.routedeventhandler?view=winrt-18362) (choose C++/WinRT from the Language drop-down in the upper-right corner of the webpage).

```c++
struct RoutedEventHandler : winrt::Windows::Foundation::IUnknown
{
    RoutedEventHandler(std::nullptr_t = nullptr) noexcept;
    template &lt;typename L&gt; RoutedEventHandler(L lambda);
    template &lt;typename F&gt; RoutedEventHandler(F* function);
    template &lt;typename O, typename M&gt; RoutedEventHandler(O* object, M method);
    void operator()(winrt::Windows::Foundation::IInspectable const& sender,
        winrt::Windows::UI::Xaml::RoutedEventArgs const& e) const;
};
```

But when I click that link, it instead shows just:
```c++
class RoutedEventHandler : MulticastDelegate
```

Is the language projection for C++/WinRT in the API documentation broken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a5d7765-efa0-3077-7c2c-5e9b8341a340
* Version Independent ID: 4e73db08-5398-9416-d20e-0680ceb5e429
* Content: [Handle events by using delegates in C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/handle-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/handle-events.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by davidmatson** [comment] 2020-04-29 00:00
Here's another one that appears to be broken:
https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperationwithprogress-2?view=winrt-18362

It shows only:
```c++
template <typename TResult, typename TProgress>
__interface IAsyncOperationWithProgress : IAsyncInfo
```

**Comment by stevewhims** [comment] 2020-04-29 02:13
Hi, @davidmatson, and thanks for filing this issue. Yes this looks like a regression in our build system that I hadn't spotted before. I'll follow up with the content engineers about it.

I'll track that work internally, so I'll go ahead and close this.

Thanks again!
-Steve

**Closed as completed by stevewhims** 2020-04-29 02:13 UTC
Labels: doc-bug, product-feedback, uwp/prod, platform/tech, Pri2

**Comment by Keeneau66** [comment] 2021-10-25 00:30
The link in the document "Handle events by using delegates in C++/WinRT" again leads to the "MulticastDelegate" wording rather than the syntax block and the associated explanations. I'm sure that I got to the page with the syntax box and the explanations by following that link only a couple of weeks ago.
