### ISSUE TITLE
Icon codes are not up to date

### ISSUE THREAD

**Issue by nikolaGrancharov** [MicrosoftDocs/windows-uwp#2043] opened 2019-10-25 22:31 UTC
I have just downloaded the "Fabric External MDL2 Assets"  font from this site, and many of the codes that are provided here do not match the codes that are actually in the font. I am checking them with "Charecter Mapp"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by kmahone** [comment] 2020-01-08 19:31
@YuliKl please follow up.

**Comment by YuliKl** [comment] 2020-01-08 23:57
@nikolaGrancharov, can you provide more details of what you see on Character Map? What do you expect to see that's different? Screen grabs or detailed steps to repro would be really helpful for us to  better understand the problem.

**Comment by nikolaGrancharov** [comment] 2020-01-09 20:20
There is a point after witch the codes stop working. First picture shows that to some point most codes match (i have not tryed all of them, but pritty mutch every one before "F19D" works):
![image](https://user-images.githubusercontent.com/7940737/72100551-7d7a5180-332b-11ea-9a3c-70747fb3f18c.png)
After that point, the codes stop matching:
![image](https://user-images.githubusercontent.com/7940737/72100571-89661380-332b-11ea-81ab-c30d9ff202bf.png)
and 
![image](https://user-images.githubusercontent.com/7940737/72100725-cfbb7280-332b-11ea-895c-671f08f98b17.png)

**Steps to reproduce:**

- Download the font from the link in the documentation: [https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#how-do-i-get-this-font](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#how-do-i-get-this-font) 
From the section "How do I get this font?"

- Install the font on your computer.

- Open the "Charecter Map" on windows and find the "Segoe MDL2 Assets" from the "Font" dropdown

- Find some icon from the documentation, and search the "Unicode" code in "Charecter Map"
(the search by Unicode is under "Advanced view -> Go to Unicode")

**Expected results:**
All icons should match compleatly

**Actual result:**
Only part of the icons match

**Test codes:**
Try finding this codes in both the documentation and the "Charecter Map":
"F22E", "F270", "F406"

**Potential problem**
I have noticed that i do not have the same issue on anohter computer of mine, and after I checked, both fonts are not the same size, but with the same name:
![image](https://user-images.githubusercontent.com/7940737/72101690-fb3f5c80-332d-11ea-9017-ea07a69a3bbf.png)
I asume that you have a very old version of the font as a link in the documentation.

**Comment by nikolaGrancharov** [comment] 2020-01-13 14:26
@YuliKl Do you need more info?

**Comment by YuliKl** [comment] 2020-01-14 05:01
@nikolaGrancharov my apologies, I had missed your reply from a few days ago. I've forwarded the information you provided to the icons feature team.

**Comment by YuliKl** [comment] 2020-01-23 18:42
@nikolaGrancharov thank you for reporting this. The font up on the share is out of sync with the article. We'll work on updating the published font.

**Comment by hickeys** [comment] 2020-05-22 18:01
I just checked in with @YuliKl. I'll update as soon as I have the current list.

**Comment by Karl-Bridge-Microsoft** [comment] 2021-01-29 17:48
@hickeys - [DocBash] Is this still an issue? Did you update the topic as required?

**Comment by hickeys** [comment] 2021-05-28 21:04
Sorry for the delay. The updated font still has not been published. I'm going to close this as a duplicate of [this issue](https://github.com/MicrosoftDocs/windows-uwp/issues/2320) because that issue is the real source of the problem, and this issue only describes specific effects of the font file being out of date in the first place.

Please re-open if you think it's necessary.

**Closed as completed by hickeys** 2021-05-28 21:04 UTC
Labels: eng-triaged, needs-more-info, doc-bug, uwp/prod, design/tech, Pri1
