### ISSUE TITLE
创作清单 链接不存在

### ISSUE THREAD

**Issue by itldg** [MicrosoftDocs/windows-uwp#5095] opened 2024-08-06 09:36 UTC
### Type of issue

Outdated article

### Feedback

创作清单 链接不存在

https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md

### Page URL

https://learn.microsoft.com/zh-cn/windows/package-manager/package/manifest?tabs=minschema%2Cinstaller-example

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/package/manifest.md

### Author

@mattwojo

### Document Id

8976699b-cdba-5206-bdb0-8a0875acfe45

**Comment by mattwojo** [comment] 2024-08-29 22:57
创作清单 链接不存在 = "Creation list link does not exist"
> Investigating

**Comment by mattwojo** [comment] 2024-09-12 21:59
I need more information describing what the issue is that you have found with the manifest authoring list. Closing. Feel welcome to reopen and add more information defining the issue you have found.

请提供更多描述有关您在清单编写列表中发现的问题的信息。关闭。欢迎您重新打开并添加更多定义您所发现问题的信息。

**Closed as completed by mattwojo** 2024-09-12 21:59 UTC
Labels: Pri3
