### ISSUE TITLE
Add PowerRename in right click context menu in windows 11 (currently only present in show more options)

### ISSUE THREAD

**Issue by dpi0** [MicrosoftDocs/windows-uwp#3665] opened 2022-02-14 08:12 UTC
I use this very often and it is really inconvenient to each time go through 3-4 steps just to reach to the same thing done previously with 2 clicks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment] 2022-03-22 05:51
Duplicate of https://github.com/microsoft/PowerToys/issues/13168

**Comment by mattwojo** [comment] 2022-05-19 20:17
Closing as this is more of a feature request for the product repo than a documentation update. Please see: https://github.com/microsoft/PowerToys/issues/13168

**Closed as completed by mattwojo** 2022-05-19 20:17 UTC
Labels: product-feedback, dev-environment/prod, Pri2, powertoys/tech
