### ISSUE TITLE
Please upgrade to WinUI 3

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/windows-uwp#4693] opened 2023-10-23 21:25 UTC
Please upgrade this walkthrough to use WinUI 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 635488bb-48b9-ec76-7a09-c545b0d2b317
* Version Independent ID: ea91feb7-3995-32fb-bc6e-99a23741e9a8
* Content: [Porting the Clipboard sample to C++/WinRT from C# (a case study) - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp)
* Content Source: [uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2023-10-23 23:46
Hi, @dr-eck, and thanks for filing this issue.

If we do anything here, it'd be in addition to the current topic rather than instead of it. So I'm wondering what a new topic would look like. Presumably you're thinking of taking a WinUI 3 sample app that's written in C#, and porting that app to C++/WinRT? The Clipboard sample app used in this topic is UWP-only. So we'd need to come up with a WinUI 3 sample to port. And then, this topic is a companion topic to [Move to C++/WinRT from C#](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp). I'm thinking that that topic, together with this case study, cover just about anything you need to know about moving from C# to C++/WinRT, regardless of platform. So I'm not sure that another topic (essentially a dupe of this one, but for a different and equally important platform) would yield much return for the investment. And it would be a significant investment.

Are you more interested in the aspect of porting code from C# to C++/WinRT, or the use of the Clipboard APIs in this sample?

Thanks!
-Steve

**Comment by dr-eck** [comment] 2023-10-25 01:34
Thanks for responding.  It's my understanding that in the future UWP will become less important and the Windows App SDK will become more important, so I'm trying WinUI 3 and C++/WinRT.  The more examples of that I can get, the better.  BTW, as a learning exercise, I'm porting Petzold's code from "Programming Windows 6th ed." to C++/WinRT + WinUI 3.  I'm on chapter 7 and stuck on the first example, which is the first use of a context menu.  C++/WinRT/WinUI3 code for this page would be most helpful:  https://learn.microsoft.com/en-us/windows/apps/design/controls/menus-and-context-menus

**Comment by stevewhims** [comment] 2023-11-16 21:49
Thanks, @dr-eck. I took a look at the "Menus and context menus" topic that you linked. That topic is already focused on WinUI 3. The links to APIs go to the WinUI 3 version of the control, (not the UWP/WinUI 2 version). And that topic is in the "Design" section, so it's intentionally written to help with design decisions (not later coding tasks). A topic like that wouldn't contain code, so it wouldn't be focused on C# versus C++/WinRT (or both).

For topics that are aimed at developers, are there particular topics that aren't easy to use b/c they lack C++/WinRT code examples? Or topics that seem inappropriately scoped to just WinUI 3 or UWP? If so, then please create an issue on those topics.

I'll go ahead and close this one.

Thanks!
-Steve

**Closed as completed by stevewhims** 2023-11-16 21:49 UTC
Labels: uwp/prod, platform/tech, Pri2
