### ISSUE TITLE
Audio mutes when window minimized

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/windows-uwp#1175] opened 2018-11-05 10:34 UTC
Hi,
I'm using the `MediaPlayer` element to play a sequence of various audio files. After enabling the _Background Media Playback_ capability, the audio will mute once I minimize the app window (on Windows).
Please elaborate this tutorial to indicate what's supposed to work and what not, or perhaps it's not clear what steps have to be taken to make the `MediaPlayer` continue play audio in the background.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cec2ecd-7c7b-8b22-d592-17ef1776c342
* Version Independent ID: a55428d6-9091-0f58-78b6-bdad27002bc8
* Content: [Play media in the background - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/background-audio#requirements-for-background-audio)
* Content Source: [windows-apps-src/audio-video-camera/background-audio.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/background-audio.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment] 2020-08-28 17:33
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. 

GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) site is the home for technical questions and answers at Microsoft.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.

**Closed as completed by drewbatgit** 2020-08-28 17:33 UTC
Labels: doc-bug, uwp/prod, Pri2
