### ISSUE TITLE
switching node version with windows nvm - Access is denied.

### ISSUE THREAD

**Issue by kdpuvvadi** [MicrosoftDocs/windows-uwp#4001] opened 2022-08-18 04:50 UTC
To switch the `node` version with `windows-nvm` with `nvm use 16.14.2`  only working with elevated shell otherwise getting 

```powershell
exit status 5: Access is denied.

exit status 5: Access is denied.
```

i'm glad to open a pr if you'd like. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745b8a68-b43b-83d2-54b6-32b3d2a35491
* Version Independent ID: 599d0cee-8710-86ef-8093-fe1b08e4aa90
* Content: [Set up NodeJS on native Windows](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows)
* Content Source: [hub/dev-environment/javascript/nodejs-on-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment] 2022-08-23 17:56
Strange. Just looked it up on the windows-nvm repo and appears that it may be an nvm version issue: https://github.com/coreybutler/nvm-windows/issues/767

**Comment by mattwojo** [comment] 2022-08-23 18:01
Sounds like the nvm community is working on fixing this elevation requirement right now, so I'm hesitant to change these docs if the issue is going to be resolved soon. They're recommending just to [use 1.1.7 for now](https://github.com/coreybutler/nvm-windows/issues/700#issuecomment-1003328514). Maybe worth adding a note about in this get started with NodeJS on Windows doc...? 
Up for filing a PR? Otherwise, I can add something in next week. Thanks for filing the issue and bringing to attention!

**Comment by kdpuvvadi** [comment] 2022-08-24 04:41
I think it's worth adding note until it's resolved at the upstream. 

> Up for filing a PR?

Sure, will do that.

**Comment by mattwojo** [comment] 2022-09-09 23:58
Closing based on your PR with this info and link being merged. https://github.com/MicrosoftDocs/windows-dev-docs/pull/4014
Thanks for figuring this out and contributing so others won't be confused!

**Closed as completed by mattwojo** 2022-09-09 23:58 UTC
Labels: dev-environment/prod, Pri1, windows-javascript/tech
