### ISSUE TITLE
Unicode Characters not Displaying

### ISSUE THREAD

**Issue by mthanson8333** [MicrosoftDocs/windows-uwp#2876] opened 2020-12-20 23:20 UTC
I had to amend the code to include the following headers:
#include <fcntl.h>
#include <io.h>

I had to include the following line to set the console mode:

int old = _setmode(_fileno(stdout), _O_U16TEXT);

I did not like doing this since this is C-style. Reference: https://www.youtube.com/watch?v=_UdN1MTYBMY

Does anybody have any suggestions?

Reference:
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-12-20 23:56
Hi, @mthanson8333, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the particular documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions (or requests for help) regarding your specific scenario, like this, one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2020-12-20 23:56 UTC
Labels: doc-bug, uwp/prod, platform/tech
