### ISSUE TITLE
Consuming C++/WinRT from C#

### ISSUE THREAD

**Issue by brabebhin** [MicrosoftDocs/windows-uwp#3880] opened 2022-06-10 07:31 UTC
Basically this is a complete regression from the tooling we used to have with C++/CX and UWP. I don't see any reason why Visual Studio should not be able to do all this on its own, with no manual steps and interventions from the developers, the way it used to do and still does with C++/CX and C#. Please consider abstracting this whole process from the developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Version Independent ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Content: [Generate a C# projection from a C++/WinRT component, distribute as a NuGet for .NET 5 and later apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-06-10 18:13
Hi, @brabebhin, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, you'd use this channel if the documentation itself is incorrect or incomplete.

But for feedback or questions about the product/feature/APIs, like this, you can click **Send feedback about** \> **This product** (instead of **This page**), and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-06-10 18:13 UTC
Labels: apps/tech, Pri2, reunion/prod

**Comment by brabebhin** [comment] 2022-06-10 18:17
Oh ok sorry. The ui in the docs is not very straightforward.
