### ISSUE TITLE
Incomplete directions to locate and install C++/WinRT extension.

### ISSUE THREAD

**Issue by noelgifford** [MicrosoftDocs/windows-uwp#345] opened 2018-03-19 04:09 UTC
The documentation states "you'll need to download and install the C++/WinRT Visual Studio Extension (VSIX) from the Visual Studio Marketplace."

This statement isn't enough to locate the extension in the Visual Studio Marketplace.
I was unable to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6f7d77e-7253-cfa2-ef6f-b58820138faa
* Version Independent ID: deb39be4-4af1-17ff-cd4e-6bb998f76d9e
* Content: [Events; how to author and handle them in C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/events-author-handle)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/events-author-handle.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/events-author-handle.md)
* Service: **unspecified**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2018-03-19 04:33
Hi, Noel! Yes, that's true, and in fact it's by design right at this moment but only because C++/WinRT (and the documentation for it) is still in a pre-release form. The documentation is marked pre-release, but we do understand that folks are keen to evaluate the technology and for that reason C++/WinRT is available in Windows Insider builds of the Windows SDK. Until the general availability of C++/WinRT (when the VSIX is expected to be available), for developing with C++/WinRT both inside and outside Visual Studio, I would recommend the great info that you can find on https://kennykerr.ca/articles/ and https://moderncpp.com/.

**Comment by stevewhims** [comment] 2018-03-19 21:03
I'll close this, since we're still in the pre-release phase. Thanks for looking at the C++/WinRT content!

**Closed as completed by stevewhims** 2018-03-19 21:03 UTC
